import type { BusinessId, ModifierKind, UpgradeTarget } from "./types";

type UpgradeRow = readonly [string, UpgradeTarget, number, ModifierKind, number];

const n = (amount: number, exponent: number) => amount * 10 ** exponent;

export const europeBusinessIds = [
  "dutch-lithography-lab",
  "alpine-gravity-booth",
  "nordic-payroll-clone",
  "continental-rail-express",
  "riviera-oxygen-bar",
  "north-sea-helium-farm",
  "alpine-cheese-mine",
  "europa-park-resort",
  "transylvanian-data-colony",
  "cern-giant-laser",
] satisfies BusinessId[];

const [
  shoes,
  booth,
  clone,
  express,
  oxygen,
  helium,
  cheese,
  park,
  colony,
  laser,
] = europeBusinessIds;

const businessTargets = [
  shoes,
  booth,
  clone,
  express,
  oxygen,
  helium,
  cheese,
  park,
  colony,
  laser,
] as const;

const cashTier = (
  label: string,
  exponent: number,
  amounts: readonly number[],
  multiplier: number,
): UpgradeRow[] =>
  businessTargets.map((target, index) => [
    `${label} ${index + 1}`,
    target,
    n(amounts[index], exponent),
    "profit",
    multiplier,
  ]);

export const europeCashUpgradeRows: UpgradeRow[] = [
  ["Shiny Buckles", shoes, n(332.5, 3), "profit", 3],
  ["Soft Soulful Music", booth, n(665, 3), "profit", 3],
  ["Open Late", clone, n(1.33, 6), "profit", 3],
  ["Dark Matter Engines", express, n(6.65, 6), "profit", 3],
  ["Moon Beverages", oxygen, n(13.3, 6), "profit", 3],
  ["Benevolent AIs", helium, n(33.25, 6), "profit", 3],
  ["Crackers", cheese, n(1.665, 9), "profit", 3],
  ["Low Gravity Mascots", park, n(133, 9), "profit", 3],
  ["Fresh Meat", colony, n(665, 9), "profit", 3],
  ["Mini-Clone Assistants", laser, n(3.3, 12), "profit", 3],
  ["Air Filters", "all", n(10, 12), "profit", 9],
  ["Limited Warranties", shoes, n(30, 12), "profit", 3],
  ["More Colors", booth, n(70, 12), "profit", 3],
  ["Friendly-Gene Splicing", clone, n(150, 12), "profit", 3],
  ["Sarcastic Robot", express, n(275, 12), "profit", 3],
  ["Cushy Barstools", oxygen, n(433, 12), "profit", 3],
  ["Crash-Proof Harvesters", helium, n(266, 12), "profit", 3],
  ["Tea", cheese, n(665, 12), "profit", 3],
  ["Trampoline Land", park, n(931, 12), "profit", 3],
  ["Brush Kiosks", colony, n(2, 15), "profit", 3],
  ["Underground Lair", laser, n(3, 15), "profit", 3],
  ["Monorail To Earth", "all", n(7, 15), "profit", 9],
  ["Luna Kahuna", "all", n(13, 15), "angelEffectiveness", 1],
  ["Almoond Milk", "all", n(500, 18), "profit", 9],
  ["Cleat Upgrades", shoes, n(26, 21), "profit", 3],
  ["Mars Gravity Setting", booth, n(67, 21), "profit", 3],
  ["Celebrity DNA Samples", clone, n(93, 21), "profit", 3],
  ["Adorable Fuel Generator", express, n(133, 21), "profit", 3],
  ["Easy Mooney", "all", n(1, 72), "profit", 9],
  ["Rank And File", "all", n(3, 81), "angelEffectiveness", 3],
  ...cashTier("Quattuorvigintillion Expansion", 75, [25, 60, 177, 239, 432, 801, 2_000, 8_000, 22_000, 59_000], 3),
  ["Crescent Hats", "all", n(444, 78), "profit", 9],
  ...cashTier("Quadragintillion Expansion", 123, [1, 7, 29, 66, 129, 233, 555, 900, 3_000, 20_000], 3),
  ["The Mega Upgrade", "all", n(10, 123), "profit", 15],
  ["Giant Domes", "all", n(111, 129), "profit", 9],
  ["Digimoon", "all", n(1, 135), "profit", 9],
  ...cashTier("Quinquadragintillion Expansion", 138, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3),
  ["Thneed Sales", "all", n(100, 138), "profit", 9],
  ...cashTier("Sexquadragintillion Expansion", 141, [1, 3, 7, 25, 75, 151, 300, 600, 900, 1_200], 3),
  ["Moonagement", "all", n(1, 153), "profit", 9],
  ...cashTier("Trequinquagintillion Expansion", 159, [23, 47, 11, 24, 48, 95, 191, 383, 767, 5_000], 5),
  ["Lunatics Anonymous", "all", n(125, 162), "profit", 9],
  ["Harvest Moon", "all", n(1, 165), "profit", 9],
  ...cashTier("Sexquinquagintillion Expansion", 168, [1, 14, 114, 234, 444, 888, 23_000, 99_000, 423_000, 567_000], 3),
  ["Celestial Body", "all", n(899, 171), "profit", 9],
  ...cashTier("Novemquinquagintillion Expansion", 177, [1, 3, 9, 27, 81, 234, 356, 432, 567, 836], 3),
  ["Cookies", "all", n(1, 180), "profit", 9],
  ["Grants Wishes", shoes, n(10, 183), "profit", 15],
  ["Cleans Your Teeth", booth, n(100, 183), "profit", 15],
  ["Do Your Taxes", clone, n(1, 186), "profit", 15],
  ["OP Deliveries", express, n(10, 186), "profit", 15],
  ["Self-Breathing Air", oxygen, n(100, 186), "profit", 15],
  ["Ambition Crops", helium, n(1, 189), "profit", 15],
  ["The Cheese Stands Alone", cheese, n(10, 189), "profit", 15],
  ["Cryo-Frozen Host", park, n(100, 189), "profit", 15],
  ["Romantic Subplot", colony, n(1, 192), "profit", 15],
  ["Big Red Button", laser, n(10, 192), "profit", 15],
  ["The Very Large Upgrade", "all", n(100, 192), "profit", 999],
];

export const europeAngelUpgradeRows: UpgradeRow[] = [
  ["It Begins Again", "all", n(11, 3), "profit", 3],
  ["Sacred Steps", shoes, n(222, 3), "profit", 3],
  ["Unseen Force", booth, n(3, 6), "profit", 3],
  ["Soul Infusions", clone, n(4, 6), "profit", 3],
  ["On Heavenly Wings", express, n(55, 6), "profit", 3],
  ["Spirits", oxygen, n(666, 6), "profit", 3],
  ["Holy Ground", helium, n(7, 9), "profit", 3],
  ["Connoisseurs", cheese, n(88, 9), "profit", 3],
  ["Group Discounts", park, n(999, 9), "profit", 3],
  ["BBQ Wings", colony, n(1, 12), "profit", 3],
  ["Target Practice", laser, n(11, 12), "profit", 3],
  ["Lunatics", "all", n(123, 12), "profit", 3],
  ["Booth Swap", booth, n(50, 18), "owned", 10],
  ["Express Swap", express, n(50, 18), "owned", 10],
  ["Farm Swap", helium, n(50, 18), "owned", 10],
  ["Park Swap", park, n(50, 18), "owned", 10],
  ["Laser Swap", laser, n(50, 18), "owned", 10],
  ["Sandal Line", shoes, n(1, 21), "profit", 3],
  ["Weightless Wonderment", booth, n(9, 21), "profit", 3],
  ["Divine Division", clone, n(27, 21), "profit", 3],
  ["Miraculous Prices", express, n(99, 21), "profit", 3],
  ["Club Memberships", oxygen, n(180, 21), "profit", 3],
  ["Extra Hands", helium, n(222, 21), "profit", 3],
  ["Cheap Labor", cheese, n(343, 21), "profit", 3],
  ["Fast Pass-age", park, n(477, 21), "profit", 3],
  ["Moon Pious", "all", n(2, 33), "profit", 3],
  ["Booth Boost", booth, n(100, 33), "owned", 10],
  ["Express Boost", express, n(100, 33), "owned", 10],
  ["Farm Boost", helium, n(100, 33), "owned", 10],
  ["Park Boost", park, n(100, 33), "owned", 10],
  ["Laser Boost", laser, n(100, 33), "owned", 10],
  ["Seraphic Shoes", shoes, n(5, 36), "profit", 3],
  ["Angel-sized Booths", booth, n(19, 36), "profit", 3],
  ["Guardian Clones", clone, n(88, 36), "profit", 3],
  ["Celestial Couriers", express, n(144, 36), "profit", 3],
  ["Angel Karaoke", oxygen, n(201, 36), "profit", 3],
  ["Good And Farmful Servant", helium, n(333, 36), "profit", 3],
  ["Cherubic Carters", cheese, n(400, 36), "profit", 3],
  ["Righteous Prices", park, n(588, 36), "profit", 3],
  ["Investor Tours", colony, n(701, 36), "profit", 3],
  ["Hallowed Hollower", laser, n(911, 36), "profit", 3],
  ["Devouted Descent", "all", n(50, 39), "profit", 9],
  ["Booth Trade", booth, n(5, 42), "owned", 10],
  ["Express Trade", express, n(5, 42), "owned", 10],
  ["Farm Trade", helium, n(5, 42), "owned", 10],
  ["Park Trade", park, n(5, 42), "owned", 10],
  ["Laser Trade", laser, n(5, 42), "owned", 10],
  ["Holy Holes", shoes, n(3, 45), "profit", 5],
  ["Gilded Gravity", booth, n(6, 45), "profit", 5],
  ["Copy Paste", clone, n(12, 45), "profit", 5],
  ["Heavenly Crew", express, n(24, 45), "profit", 5],
  ["Designated Fliers", oxygen, n(48, 45), "profit", 5],
  ["Angel Crops", helium, n(96, 45), "profit", 5],
  ["Holy Cheese", cheese, n(192, 45), "profit", 5],
  ["Blessed Merchandise", park, n(384, 45), "profit", 5],
  ["Winged Wolves", colony, n(768, 45), "profit", 5],
  ["Death From Above", laser, n(14, 48), "profit", 5],
  ["Salivate-tion", "all", n(500, 48), "profit", 9],
  ["Sonata", "all", n(100, 51), "profit", 9],
  ...businessTargets.map<UpgradeRow>((target, index) => [
    `Heck-Of-A-Deal ${index + 1}`,
    target,
    n(5, 54),
    "owned",
    50,
  ]),
  ["Blessed Soles", shoes, n(100, 54), "profit", 3],
  ["Holy Infusion", booth, n(200, 54), "profit", 3],
  ["Blessed Copies", clone, n(300, 54), "profit", 3],
  ["Holy Ship", express, n(400, 54), "profit", 3],
  ["Blessed Bartop", oxygen, n(500, 54), "profit", 3],
  ["Holy Handplanted", helium, n(600, 54), "profit", 3],
  ["Blessed Swiss", cheese, n(700, 54), "profit", 3],
  ["Holy Mackrel", park, n(800, 54), "profit", 3],
  ["Holy Sheep Pelts", colony, n(900, 54), "profit", 3],
  ["Blessed Spectrometer", laser, n(1, 57), "profit", 3],
  ["CereMoonial Rites", "all", n(316, 57), "profit", 3],
  ["Divine Inspiration", "all", n(1, 60), "profit", 9],
  ...businessTargets.map<UpgradeRow>((target, index) => [
    `${index + 1} ZIPPITY`,
    target,
    n(100, 63),
    "owned",
    75,
  ]),
  ["Retroactive Sacrifice", "all", n(1, 66), "profit", 3],
  ["Sacred Laces", shoes, n(1, 69), "profit", 3],
  ["Hallowed Air Filters", booth, n(2, 69), "profit", 3],
  ["Sacred DNA", clone, n(4, 69), "profit", 3],
  ["Hallowed Captain's Chair", express, n(8, 69), "profit", 3],
  ["Sacred Thrones", oxygen, n(16, 69), "profit", 3],
  ["Hallowed Storm Shelter", helium, n(32, 69), "profit", 3],
  ["Sacred Brie", cheese, n(64, 69), "profit", 3],
  ["Hallowed Out Castle", park, n(128, 69), "profit", 3],
  ["Sacred Snazzy Scarves", colony, n(256, 69), "profit", 3],
  ["Hollower", laser, n(512, 69), "profit", 3],
  ["Sacrifinanical Advice", "all", n(1, 72), "profit", 9],
  ["Booth Bargain", booth, n(5, 75), "owned", 50],
  ["Express Bargain", express, n(5, 75), "owned", 50],
  ["Bar Super Bargain", oxygen, n(5, 75), "owned", 100],
  ["Mine Super Bargain", cheese, n(5, 75), "owned", 100],
  ["Laser Bargain", laser, n(5, 75), "owned", 25],
  ["On The Tufted Floor", shoes, n(100, 75), "profit", 7],
  ["The Over-Booth", booth, n(200, 75), "profit", 7],
  ["Angeliclones", clone, n(400, 75), "profit", 7],
  ["Express Express", express, n(800, 75), "profit", 7],
  ["Sparkling Spirits", oxygen, n(16, 78), "profit", 7],
  ["Holy Hayers", helium, n(32, 78), "profit", 7],
  ["Light In The Dark", cheese, n(64, 78), "profit", 7],
  ["Spreading Joy", park, n(128, 78), "profit", 7],
  ["Angel Wolves", colony, n(256, 78), "profit", 7],
  ["Heavenly Glow", laser, n(512, 78), "profit", 7],
  ["A Beautiful Boost", "all", n(1, 81), "profit", 7],
  ["Express Hostile Takeover", express, n(100, 84), "owned", 100],
  ["Bar Hostile Takeover", oxygen, n(200, 84), "owned", 200],
  ["Mine Hostile Takeover", cheese, n(300, 84), "owned", 300],
  ["Shoe Holiday Sale", shoes, n(1, 87), "profit", 2],
  ["Booth Holiday Sale", booth, n(9, 87), "profit", 2],
  ["Clone Holiday Sale", clone, n(18, 87), "profit", 2],
  ["Express Holiday Sale", express, n(27, 87), "profit", 2],
  ["Bar Holiday Sale", oxygen, n(36, 87), "profit", 2],
  ["Farm Holiday Sale", helium, n(45, 87), "profit", 2],
  ["Cheese Holiday Sale", cheese, n(54, 87), "profit", 2],
  ["Park Holiday Discount", park, n(63, 87), "profit", 2],
  ["Wolf Holiday Bonus", colony, n(72, 87), "profit", 2],
  ["Lasers Don't Take Holidays", laser, n(81, 87), "profit", 2],
  ["Godspeed You Grey Emperor", "all", n(1, 90), "profit", 5],
];
