import type { BusinessId, ModifierKind, UpgradeTarget } from "./types";

type UpgradeRow = [string, UpgradeTarget, number, ModifierKind, number];

const money = (amount: number, tier: number) => amount * 10 ** (tier * 3);

const redDirt = "rare-earth-mine";
const marsies = "e-commerce-marketplace";
const men = "ev-plant";
const buggles = "drone-factory";
const heckPortal = "firewall-cloud";
const ambassadors = "livestream-agency";
const brainCation = "ai-tutor-app";
const lifePod = "smartphone-campus";
const terrorformer = "high-speed-rail-grid";

export const chinaBusinessIds = [
  redDirt,
  marsies,
  men,
  buggles,
  heckPortal,
  ambassadors,
  brainCation,
  lifePod,
  terrorformer,
] satisfies BusinessId[];

export const chinaCashUpgradeRows: UpgradeRow[] = [
  ["Shovel Extensions", redDirt, money(15, 2), "profit", 33],
  ["Oiler Oil", marsies, money(500, 2), "profit", 33],
  ["Testosterone Cologne", men, money(100, 3), "profit", 33],
  ["Extra Tall Fences", buggles, money(19, 4), "profit", 33],
  ["Warning Signs", heckPortal, money(1, 5), "profit", 33],
  ["Interpretors", ambassadors, money(12, 6), "profit", 33],
  ["No Chafe Restraints", brainCation, money(9, 7), "profit", 33],
  ["Free Me2 Album", lifePod, money(600, 7), "profit", 33],
  ["Genetic Modifications", terrorformer, money(3, 9), "profit", 33],
  ["Plentiful BBQs", men, money(1, 11), "profit", 66],
  ["Saddles", buggles, money(3, 12), "profit", 66],
  ["Spray Bottles", heckPortal, money(25, 13), "profit", 66],
  ["Prepackaged Doves", ambassadors, money(130, 14), "profit", 66],
  ["Friendly Neuro-Scrubbers", brainCation, money(300, 15), "profit", 66],
  ["Trendy Commercials", lifePod, money(60, 16), "profit", 66],
  ["Spider Treats", terrorformer, money(10, 17), "profit", 66],
  ["O2 In A Can", "all", money(1, 18), "profit", 33],
  ["Fancy Wheelbarrows", redDirt, money(1, 19), "profit", 999],
  ["Cake Injections", marsies, money(700, 19), "profit", 999],
  ["Video Games", men, money(900, 19), "profit", 99],
  ["Sugar Licks", buggles, money(1, 20), "profit", 99],
  ["Brimstone Filters", heckPortal, money(5, 21), "profit", 99],
  ["Olive Branches", ambassadors, money(17, 21), "profit", 99],
  ["Discount Uploads", brainCation, money(99, 21), "profit", 99],
  ["Innovative Shapes", lifePod, money(231, 21), "profit", 99],
  ["Obedience Training", terrorformer, money(333, 21), "profit", 99],
  ["Free Pretzels", "all", money(500, 22), "profit", 33],
  ["Work Gloves", redDirt, money(123, 23), "profit", 999],
  ["Super Sizers", marsies, money(246, 23), "profit", 999],
  ["Milking Machines", buggles, money(369, 23), "profit", 999],
  ["Fun Guns", ambassadors, money(2, 24), "profit", 999],
  ["Nose Implants", brainCation, money(3, 24), "profit", 999],
  ["Oxygen Service Plans", lifePod, money(12, 24), "profit", 999],
  ["Spider Houses", terrorformer, money(23, 24), "profit", 999],
  ["Novelty Bobbleheads", "all", money(1, 25), "profit", 66],
  ["Mullet Installer", redDirt, money(5, 33), "profit", 33],
  ["Splash Proof Friers", marsies, money(125, 33), "profit", 33],
  ["BBQ Sauce Stocks", men, money(450, 33), "profit", 33],
  ["Squeeze Toys", buggles, money(625, 33), "profit", 33],
  ["Friendship Invasion", ambassadors, money(3, 34), "profit", 33],
  ["Attractive Faux Spouses", brainCation, money(25, 34), "profit", 33],
  ["New Charge Cables", lifePod, money(100, 34), "profit", 33],
  ["Mars Cars", "all", money(100, 35), "profit", 33],
  ["Big Ol' Buckets", redDirt, money(1, 36), "profit", 77],
  ["Mandatory Staff Sing Alongs", marsies, money(4, 36), "profit", 77],
  ["Gunmetal Utensils", men, money(55, 36), "profit", 77],
  ["Buggle Drives", buggles, money(90, 36), "profit", 77],
  ["Thoughtful Gifts", ambassadors, money(210, 36), "profit", 77],
  ["Inconspicous Turbans", brainCation, money(431, 36), "profit", 77],
  ["Smile Lessons", lifePod, money(777, 36), "profit", 77],
  ["Lucky Stars", "all", money(500, 37), "profit", 777],
  ["Carbon Fiber Lassos", buggles, money(5, 43), "profit", 33],
  ["Rainbows", ambassadors, money(35, 43), "profit", 33],
  ["Austrian Accent-er", brainCation, money(177, 43), "profit", 33],
  ["Siriously Friendly AI", lifePod, money(569, 43), "profit", 33],
  ["Backhoe With Rockets", redDirt, money(714, 43), "profit", 33],
  ["Creamcheese Sprayer", marsies, money(976, 43), "profit", 33],
  ["Rocket Golf Carts", men, money(1, 44), "profit", 33],
  ["Cheap Water", "all", money(50, 44), "profit", 33],
  ["Dump Tracks", redDirt, money(1, 47), "profit", 66],
  ["Smarmy Mascot", marsies, money(2, 47), "profit", 66],
  ["Pirate Flags", men, money(6, 47), "profit", 66],
  ["Rodeo Clowns", buggles, money(9, 47), "profit", 66],
  ["Ear Plugs", ambassadors, money(49, 47), "profit", 66],
  ["Robo-Taxi Upgrades", brainCation, money(300, 47), "profit", 66],
  ["Free Tortoisenecks", lifePod, money(700, 47), "profit", 66],
  ["President Carter", "all", money(300, 48), "profit", 55],
  ["New Labels", redDirt, money(5, 51), "profit", 99],
  ["FDM Deregulation", marsies, money(14, 51), "profit", 99],
  ["Military Hardware", men, money(66, 51), "profit", 99],
  ["Genetic Engineering", buggles, money(88, 51), "profit", 99],
  ["Karaoke Machines", ambassadors, money(250, 51), "profit", 99],
  ["Mutant Slums", brainCation, money(444, 51), "profit", 99],
  ["Fancy Logo", lifePod, money(653, 51), "profit", 99],
  ["Free Cookies", "all", money(1, 53), "profit", 15],
  ["Flashy Sandbags", redDirt, money(1, 56), "profit", 77],
  ["Shiny Bibs", marsies, money(3, 56), "profit", 77],
  ["Carbon Nanotube Mugs", men, money(9, 56), "profit", 77],
  ["Fancy Feed", buggles, money(19, 56), "profit", 77],
  ["Power Ties", ambassadors, money(36, 56), "profit", 77],
  ["Brain Drains", brainCation, money(99, 56), "profit", 77],
  ["Magnetic Plugs", lifePod, money(279, 56), "profit", 77],
  ["Trees", "all", money(400, 56), "profit", 25],
  ["Anti-Grav Spades", redDirt, money(1, 60), "profit", 999],
  ["Sticks", marsies, money(5, 60), "profit", 999],
  ["Lightning Shooters", men, money(8, 60), "profit", 999],
  ["Petting Zoo", buggles, money(10, 60), "profit", 999],
  ["Sensitivity Training", ambassadors, money(66, 60), "profit", 999],
  ["Magnets", brainCation, money(153, 60), "profit", 999],
  ["Is there life on Mars?", lifePod, money(372, 60), "profit", 999],
  ["Test Spiders 11", terrorformer, money(500, 60), "profit", 999],
  ["Mars Movers", redDirt, money(6, 66), "profit", 33],
  ["Beer-batter Formula", marsies, money(25, 66), "profit", 33],
  ["Easy-On Muscles", men, money(80, 66), "profit", 33],
  ["Trusty Buggle-Dogs", buggles, money(170, 66), "profit", 33],
  ["Diplomacy Simulators", ambassadors, money(439, 66), "profit", 33],
  ["$10 Rebate", brainCation, money(650, 66), "profit", 33],
  ["More Marketing", lifePod, money(900, 66), "profit", 33],
  ["Big Old Lasers", terrorformer, money(25, 67), "profit", 33],
  ["KLAATU Drones", "all", money(250, 67), "profit", 9],
  ["Dirt Magnets", redDirt, money(1, 70), "profit", 22],
  ["Mega Sized", marsies, money(11, 70), "profit", 22],
  ["Micro-Breeds", buggles, money(222, 70), "profit", 22],
  ["Elocution Lessons", ambassadors, money(333, 70), "profit", 22],
  ["A CHOPPA", brainCation, money(444, 70), "profit", 22],
  ["Audience Engagment", lifePod, money(555, 70), "profit", 22],
  ["Web Ornaments", terrorformer, money(666, 70), "profit", 22],
  ["Magnetosphere", "all", money(1, 71), "profit", 66],
  ["All Terrain Scoopers", redDirt, money(10, 73), "profit", 44],
  ["Drone Delivery", marsies, money(20, 73), "profit", 44],
  ["Funny Hats", buggles, money(40, 73), "profit", 44],
  ["Revealing Robes", ambassadors, money(60, 73), "profit", 44],
  ["Good Lawyers", brainCation, money(150, 73), "profit", 44],
  ["Hot Tubs", lifePod, money(356, 73), "profit", 44],
  ["Juicy Space Flies", terrorformer, money(900, 73), "profit", 44],
  ["Earth Independence", "all", money(6, 74), "profit", 777],
  ["The Mega Dirt Upgrade", redDirt, money(1, 75), "profit", 999],
  ["The Mega Marsie Upgrade", marsies, money(1, 76), "profit", 999],
  ["The Mega Buggle Upgrade", buggles, money(1, 77), "profit", 999],
  ["The Mega Ambassador Upgrade", ambassadors, money(1, 78), "profit", 999],
  ["The Mega Brain-cation Upgrade", brainCation, money(1, 79), "profit", 999],
  ["The Mega LiFE Pod Upgrade", lifePod, money(1, 80), "profit", 999],
  ["The Mega Terrorformer Upgrade", terrorformer, money(1, 81), "profit", 999],
];

export const chinaAngelUpgradeRows: UpgradeRow[] = [
  ["Help From Above", "all", money(100, 3), "profit", 3],
  ["More Help From Above", "all", money(100, 5), "profit", 3],
  ["Holy Diggers", redDirt, money(1, 7), "profit", 5],
  ["Holy Friers", marsies, money(2, 7), "profit", 5],
  ["Wingmen", men, money(4, 7), "profit", 5],
  ["Holy Wranglers", buggles, money(8, 7), "profit", 5],
  ["Conflict of Interest", heckPortal, money(16, 7), "profit", 5],
  ["Holy Interpretors", ambassadors, money(32, 7), "profit", 5],
  ["Holy Implanters", brainCation, money(64, 7), "profit", 5],
  ["Holy Cameramen", lifePod, money(128, 7), "profit", 5],
  ["Holy Ranch Hands", terrorformer, money(256, 7), "profit", 5],
  ["Holy Boosters", "all", money(1, 8), "profit", 3],
  ["Angelic Work Crew", redDirt, money(1, 10), "profit", 7],
  ["Consumers", marsies, money(3, 10), "profit", 7],
  ["Fashion Consultants", men, money(9, 10), "profit", 7],
  ["Buggle Massagers", buggles, money(27, 10), "profit", 7],
  ["Protal Guards", heckPortal, money(100, 10), "profit", 7],
  ["Little Sandwich Servers", ambassadors, money(200, 10), "profit", 7],
  ["Disposable Henchmen", brainCation, money(400, 10), "profit", 7],
  ["Early Adopters", lifePod, money(600, 10), "profit", 7],
  ["Web Washers", terrorformer, money(900, 10), "profit", 7],
  ["Delivery Angels", "all", money(1, 12), "profit", 5],
  ["Oxygen Wranglers", "all", money(1, 14), "profit", 3],
  ["Brushers", redDirt, money(3, 15), "profit", 3],
  ["Graceful Cashiers", marsies, money(12, 15), "profit", 3],
  ["Palm Leaf Fanners", men, money(29, 15), "profit", 3],
  ["Buggle Pokes", buggles, money(136, 15), "profit", 3],
  ["If You Say So", heckPortal, money(311, 15), "profit", 3],
  ["Dignitary Chaffeurs", ambassadors, money(555, 15), "profit", 3],
  ["Nurses", brainCation, money(789, 15), "profit", 3],
  ["Pod Installers", lifePod, money(25, 16), "profit", 3],
  ["Terrorformer Bait", terrorformer, money(100, 16), "profit", 3],
  ["Wandering Salesmen", "all", money(100, 18), "profit", 5],
  ["Dirt Quality Assurance", redDirt, money(1, 20), "profit", 5],
  ["Chocolate Injectors", marsies, money(5, 20), "profit", 5],
  ["Landlords", men, money(45, 20), "profit", 5],
  ["Buggle Milkers", buggles, money(66, 20), "profit", 5],
  ["Containment Units", heckPortal, money(99, 20), "profit", 5],
  ["Secret Spies", ambassadors, money(175, 20), "profit", 5],
  ["Brain Fixers", brainCation, money(280, 20), "profit", 5],
  ["Pod People", lifePod, money(420, 20), "profit", 5],
  ["Atmosphere Testers", terrorformer, money(700, 20), "profit", 5],
  ["Mars Angel, Will You Be Mine", "all", money(5, 21), "profit", 5],
  ["Holy Mars-aroni", "all", money(100, 24), "profit", 7],
  ["Keeping On", redDirt, money(1, 26), "profit", 9],
  ["Food Testers", marsies, money(10, 26), "profit", 9],
  ["Holy Bros", men, money(20, 26), "profit", 9],
  ["Buggle Washers", buggles, money(100, 26), "profit", 9],
  ["Heck Is A Heck Of A Drag", heckPortal, money(200, 26), "profit", 9],
  ["Body Guards", ambassadors, money(400, 26), "profit", 9],
  ["Resistance Members", brainCation, money(800, 26), "profit", 9],
  ["Hug Givers", lifePod, money(16, 27), "profit", 9],
  ["Fly Catchers", terrorformer, money(222, 27), "profit", 9],
  ["Holy Synergy", "all", money(666, 27), "profit", 9],
  ["Mars Rising", "all", money(1, 28), "profit", 9],
  ["Helpful Hand", redDirt, money(2, 30), "profit", 15],
  ["Burn Proof Workers", marsies, money(14, 30), "profit", 15],
  ["Got Your Back", men, money(56, 30), "profit", 15],
  ["Good With Animals", buggles, money(112, 30), "profit", 15],
  ["Still Not Comfortable", heckPortal, money(179, 30), "profit", 15],
  ["Secret Service", ambassadors, money(298, 30), "profit", 15],
  ["Idea Men", brainCation, money(434, 30), "profit", 15],
  ["Pod Decorators", lifePod, money(620, 30), "profit", 15],
  ["Baby Sitters", terrorformer, money(808, 30), "profit", 15],
  ["Here To Serve", "all", money(1, 31), "profit", 15],
  ["That Glorious Hour", "all", money(9, 33), "profit", 9],
  ["The Last Dirt Upgrade", redDirt, money(34, 35), "profit", 21],
  ["The Last Marsies Upgrade", marsies, money(6, 35), "profit", 21],
  ["The Last Manly Upgrade", men, money(12, 35), "profit", 21],
  ["The Last Buggle Upgrade", buggles, money(24, 35), "profit", 21],
  ["The Last Heck Upgrade", heckPortal, money(69, 35), "profit", 21],
  ["The Last Ambassador Upgrade", ambassadors, money(105, 35), "profit", 21],
  ["The Last Brain Upgrade", brainCation, money(214, 35), "profit", 21],
  ["The Last LiFE Pod Upgrade", lifePod, money(333, 35), "profit", 21],
  ["The Last Terrorformer Upgrade", terrorformer, money(500, 35), "profit", 21],
  ["The End In Sight", "all", money(1, 36), "profit", 9],
  ["Praise Ares", "all", money(777, 37), "profit", 777],
];
