import type { BusinessId, ModifierKind, UpgradeTarget } from "./types";

type UpgradeRow = [string, UpgradeTarget, number, ModifierKind, number];

const money = (amount: number, tier: number) => amount * 10 ** (tier * 3);

const pandabuyAgent = "pandabuy-agent";
const sheinFactory = "shein-factory";
const wechat = "wechat";
const droneSwarm = "drone-swarm";
const tiktokAlgo = "tiktok-algo";
const huaweiPhone = "huawei-phone";
const kimi = "kimi";
const robotDog = "robot-dog";
const amdChip = "amd-chip";
const deepseek = "deepseek";

export const chinaBusinessIds = [
  pandabuyAgent,
  sheinFactory,
  wechat,
  droneSwarm,
  tiktokAlgo,
  huaweiPhone,
  kimi,
  robotDog,
  amdChip,
  deepseek,
] satisfies BusinessId[];

export const chinaCashUpgradeRows: UpgradeRow[] = [
  ["Warehouse Floor Expansion", pandabuyAgent, money(15, 2), "profit", 33],
  ["Sewing Machine Lubricant", sheinFactory, money(500, 2), "profit", 33],
  ["Mini-Program Wave", wechat, money(100, 3), "profit", 33],
  ["Geofence Override", droneSwarm, money(19, 4), "profit", 33],
  ["Watchdog Bypass", tiktokAlgo, money(1, 5), "profit", 33],
  ["Sanctions Translator", huaweiPhone, money(12, 6), "profit", 33],
  ["Long-Context Restraint Lift", kimi, money(9, 7), "profit", 33],
  ["Free Replacement Servos", robotDog, money(600, 7), "profit", 33],
  ["Weight Distillation Patch", deepseek, money(3, 9), "profit", 33],
  ["Holiday Red Envelopes", wechat, money(1, 11), "profit", 66],
  ["Auto-Pilot Saddle Mount", droneSwarm, money(3, 12), "profit", 66],
  ["Auto-Reply Bot Wave", tiktokAlgo, money(25, 13), "profit", 66],
  ["Diplomatic Olive Branch", huaweiPhone, money(130, 14), "profit", 66],
  ["Thought Polishers", kimi, money(300, 15), "profit", 66],
  ["Viral Sidewalk Demos", robotDog, money(60, 16), "profit", 66],
  ["MoE Routing Treats", deepseek, money(10, 17), "profit", 66],
  ["Cross-Provincial Logistics", "all", money(1, 18), "profit", 33],
  ["Cargo Container Upgrade", pandabuyAgent, money(1, 19), "profit", 999],
  ["TikTok Trend Injection", sheinFactory, money(700, 19), "profit", 999],
  ["Tencent Game Bundle", wechat, money(900, 19), "profit", 99],
  ["Battery Hot-Swap", droneSwarm, money(1, 20), "profit", 99],
  ["Algorithmic Heat Filter", tiktokAlgo, money(5, 21), "profit", 99],
  ["State-Sponsored Discounts", huaweiPhone, money(17, 21), "profit", 99],
  ["Discount Inference Tier", kimi, money(99, 21), "profit", 99],
  ["Modular Limb Variants", robotDog, money(231, 21), "profit", 99],
  ["RLHF Alignment Pass", deepseek, money(333, 21), "profit", 99],
  ["Free WeChat Stickers", "all", money(500, 22), "profit", 33],
  ["Customs Clearance Crew", pandabuyAgent, money(123, 23), "profit", 999],
  ["Plus-Size Drop", sheinFactory, money(246, 23), "profit", 999],
  ["Live-Stream Reconnaissance", droneSwarm, money(369, 23), "profit", 999],
  ["Hardware Encryption Module", huaweiPhone, money(2, 24), "profit", 999],
  ["Olfactory Embedding", kimi, money(3, 24), "profit", 999],
  ["Diagnostics Service Plan", robotDog, money(12, 24), "profit", 999],
  ["Sparse Expert Houses", deepseek, money(23, 24), "profit", 999],
  ["Spring Festival Promo", "all", money(1, 25), "profit", 66],
  ["QC Inspection Crew", pandabuyAgent, money(5, 33), "profit", 33],
  ["Quick-Print Dyeing", sheinFactory, money(125, 33), "profit", 33],
  ["Pay-by-Face QR", wechat, money(450, 33), "profit", 33],
  ["Sentry Drone Pack", droneSwarm, money(625, 33), "profit", 33],
  ["Belt and Road Charm Offensive", huaweiPhone, money(3, 34), "profit", 33],
  ["Companion Bot Persona", kimi, money(25, 34), "profit", 33],
  ["Hot-Swap Battery Cells", robotDog, money(100, 34), "profit", 33],
  ["Made-in-China Premium", "all", money(100, 35), "profit", 33],
  ["Bulk Order Discount Tier", pandabuyAgent, money(1, 36), "profit", 77],
  ["Mandatory KPI Karaoke", sheinFactory, money(4, 36), "profit", 77],
  ["Steel Encryption Layer", wechat, money(55, 36), "profit", 77],
  ["Decoy Drone Pack", droneSwarm, money(90, 36), "profit", 77],
  ["Banquet Hospitality", huaweiPhone, money(210, 36), "profit", 77],
  ["Plain UI Skin", kimi, money(431, 36), "profit", 77],
  ["Friendly Bark Pack", robotDog, money(777, 36), "profit", 77],
  ["Five-Year Plan Bonus", "all", money(500, 37), "profit", 777],
  ["Aerial Catch Net", droneSwarm, money(5, 43), "profit", 33],
  ["Multi-Sky Antenna", huaweiPhone, money(35, 43), "profit", 33],
  ["Vienna-Trained Translator", kimi, money(177, 43), "profit", 33],
  ["Adoption-Friendly AI", robotDog, money(569, 43), "profit", 33],
  ["Air Freight Express", pandabuyAgent, money(714, 43), "profit", 33],
  ["Synthetic Silk Coating", sheinFactory, money(976, 43), "profit", 33],
  ["Lightning Payment Rail", wechat, money(1, 44), "profit", 33],
  ["Pearl River Bandwidth", "all", money(50, 44), "profit", 33],
  ["Reshipping Service Combo", pandabuyAgent, money(1, 47), "profit", 66],
  ["Influencer Brand Mascot", sheinFactory, money(2, 47), "profit", 66],
  ["Black Market Crackdown", wechat, money(6, 47), "profit", 66],
  ["Robo-Decoy Show", droneSwarm, money(9, 47), "profit", 66],
  ["Background Noise Suppress", huaweiPhone, money(49, 47), "profit", 66],
  ["Robo Driver Persona", kimi, money(300, 47), "profit", 66],
  ["Free Carbon Shell", robotDog, money(700, 47), "profit", 66],
  ["Reform Era Throwback", "all", money(300, 48), "profit", 55],
  ["Re-Box Express Service", pandabuyAgent, money(5, 51), "profit", 99],
  ["Tariff Loophole Discovery", sheinFactory, money(14, 51), "profit", 99],
  ["Patriotic Filter Stack", wechat, money(66, 51), "profit", 99],
  ["Swarm Mesh Optimizer", droneSwarm, money(88, 51), "profit", 99],
  ["Built-In Karaoke Mode", huaweiPhone, money(250, 51), "profit", 99],
  ["Underground Eval Set", kimi, money(444, 51), "profit", 99],
  ["Custom Skin Painters", robotDog, money(653, 51), "profit", 99],
  ["Free Trade Zone", "all", money(1, 53), "profit", 15],
  ["Anti-Theft Padding", pandabuyAgent, money(1, 56), "profit", 77],
  ["Glitter Top Stitching", sheinFactory, money(3, 56), "profit", 77],
  ["Group Chat Megapacks", wechat, money(9, 56), "profit", 77],
  ["Solar Recharge Pad", droneSwarm, money(19, 56), "profit", 77],
  ["Powerstrip Hub", huaweiPhone, money(36, 56), "profit", 77],
  ["Long Memory Drain", kimi, money(99, 56), "profit", 77],
  ["Magnetic Charging Plate", robotDog, money(279, 56), "profit", 77],
  ["Pollution Offset Pledge", "all", money(400, 56), "profit", 25],
  ["Light-as-Air Packaging", pandabuyAgent, money(1, 60), "profit", 999],
  ["Recyclable Trims", sheinFactory, money(5, 60), "profit", 999],
  ["Lightning Notification Stream", wechat, money(8, 60), "profit", 999],
  ["Public Display Drone Show", droneSwarm, money(10, 60), "profit", 999],
  ["Wokeness Filter Pack", huaweiPhone, money(66, 60), "profit", 999],
  ["Attention Magnet", kimi, money(153, 60), "profit", 999],
  ["Is there life in Shenzhen?", robotDog, money(372, 60), "profit", 999],
  ["Eval Sweep 11", deepseek, money(500, 60), "profit", 999],
  ["Regional Sourcing Network", pandabuyAgent, money(6, 66), "profit", 33],
  ["Anti-Tear Fiber Mix", sheinFactory, money(25, 66), "profit", 33],
  ["Easy-On Lifestyle Brand", wechat, money(80, 66), "profit", 33],
  ["Reliable Mesh Buddies", droneSwarm, money(170, 66), "profit", 33],
  ["Diplomacy Simulators", huaweiPhone, money(439, 66), "profit", 33],
  ["¥10 Cashback Coupon", kimi, money(650, 66), "profit", 33],
  ["Sidewalk Mall Demos", robotDog, money(900, 66), "profit", 33],
  ["FP8 Mixed Precision", deepseek, money(25, 67), "profit", 33],
  ["State Visit Drones", "all", money(250, 67), "profit", 9],
  ["Hot SKU Magnet", pandabuyAgent, money(1, 70), "profit", 22],
  ["Plus-Size Catalogue", sheinFactory, money(11, 70), "profit", 22],
  ["Microdrone Variant Line", droneSwarm, money(222, 70), "profit", 22],
  ["Elocution Lessons", huaweiPhone, money(333, 70), "profit", 22],
  ["Edge Inference Module", kimi, money(444, 70), "profit", 22],
  ["Audience Engagement Loop", robotDog, money(555, 70), "profit", 22],
  ["Web Crawl Ornaments", deepseek, money(666, 70), "profit", 22],
  ["Great Firewall Polish", "all", money(1, 71), "profit", 66],
  ["Inland Provincial Routes", pandabuyAgent, money(10, 73), "profit", 44],
  ["Drone Drop-Ship", sheinFactory, money(20, 73), "profit", 44],
  ["Camouflage Skin Pack", droneSwarm, money(40, 73), "profit", 44],
  ["Translucent Glass Back", huaweiPhone, money(60, 73), "profit", 44],
  ["Legal Memory Bank", kimi, money(150, 73), "profit", 44],
  ["Heat-Resistant Coating", robotDog, money(356, 73), "profit", 44],
  ["Synthetic Reasoning Data", deepseek, money(900, 73), "profit", 44],
  ["Domestic Demand Surge", "all", money(6, 74), "profit", 777],
  ["The Mega Haul Upgrade", pandabuyAgent, money(1, 75), "profit", 999],
  ["The Mega SKU Upgrade", sheinFactory, money(1, 76), "profit", 999],
  ["The Mega Swarm Upgrade", droneSwarm, money(1, 77), "profit", 999],
  ["The Mega Diplomacy Upgrade", huaweiPhone, money(1, 78), "profit", 999],
  ["The Mega Long-Context Upgrade", kimi, money(1, 79), "profit", 999],
  ["The Mega Robot Dog Upgrade", robotDog, money(1, 80), "profit", 999],
  ["The Mega DeepSeek Upgrade", deepseek, money(1, 81), "profit", 999],
];

export const chinaAngelUpgradeRows: UpgradeRow[] = [
  ["Help From The CCP", "all", money(100, 3), "profit", 3],
  ["More Help From The CCP", "all", money(100, 5), "profit", 3],
  ["Lucky Sourcing Brokers", pandabuyAgent, money(1, 7), "profit", 5],
  ["Lucky Stitchers", sheinFactory, money(2, 7), "profit", 5],
  ["WeChat Wings", wechat, money(4, 7), "profit", 5],
  ["Lucky Drone Pilots", droneSwarm, money(8, 7), "profit", 5],
  ["Algorithmic Conflict Tuning", tiktokAlgo, money(16, 7), "profit", 5],
  ["Sacred Translators", huaweiPhone, money(32, 7), "profit", 5],
  ["Sacred Embedding Tuners", kimi, money(64, 7), "profit", 5],
  ["Sacred Onboard Cameras", robotDog, money(128, 7), "profit", 5],
  ["Sacred Open Weights", deepseek, money(256, 7), "profit", 5],
  ["Sacred Boosters", "all", money(1, 8), "profit", 3],
  ["Auspicious Logistics Crew", pandabuyAgent, money(1, 10), "profit", 7],
  ["Trend-Hungry Consumers", sheinFactory, money(3, 10), "profit", 7],
  ["Mini-Program Consultants", wechat, money(9, 10), "profit", 7],
  ["Drone Service Techs", droneSwarm, money(27, 10), "profit", 7],
  ["Portal Filter Guards", tiktokAlgo, money(100, 10), "profit", 7],
  ["Banquet Servers", huaweiPhone, money(200, 10), "profit", 7],
  ["Disposable Henchmen", kimi, money(400, 10), "profit", 7],
  ["Early Adopter Pack", robotDog, money(600, 10), "profit", 7],
  ["Pretraining Web Scrubbers", deepseek, money(900, 10), "profit", 7],
  ["Logistics Angels", "all", money(1, 12), "profit", 5],
  ["Bandwidth Wranglers", "all", money(1, 14), "profit", 3],
  ["QC Cleansing Wave", pandabuyAgent, money(3, 15), "profit", 3],
  ["Auspicious Cashiers", sheinFactory, money(12, 15), "profit", 3],
  ["Group Chat Moderators", wechat, money(29, 15), "profit", 3],
  ["Probe Drone Pack", droneSwarm, money(136, 15), "profit", 3],
  ["Submissive Moderation", tiktokAlgo, money(311, 15), "profit", 3],
  ["Dignitary Chauffeurs", huaweiPhone, money(555, 15), "profit", 3],
  ["Memory Nurses", kimi, money(789, 15), "profit", 3],
  ["Service Installers", robotDog, money(25, 16), "profit", 3],
  ["Eval Bait Tasks", deepseek, money(100, 16), "profit", 3],
  ["Wandering Salespeople", "all", money(100, 18), "profit", 5],
  ["Premium Sourcing QA", pandabuyAgent, money(1, 20), "profit", 5],
  ["Influencer Endorsement Tier", sheinFactory, money(5, 20), "profit", 5],
  ["Mini-Program Landlords", wechat, money(45, 20), "profit", 5],
  ["Surveillance Live-Streamers", droneSwarm, money(66, 20), "profit", 5],
  ["Containment Units", tiktokAlgo, money(99, 20), "profit", 5],
  ["MI Bureau Liaisons", huaweiPhone, money(175, 20), "profit", 5],
  ["Embedding Doctors", kimi, money(280, 20), "profit", 5],
  ["Loyal Owners", robotDog, money(420, 20), "profit", 5],
  ["Inference Testers", deepseek, money(700, 20), "profit", 5],
  ["China Angel, Will You Be Mine", "all", money(5, 21), "profit", 5],
  ["Sacred Hotpot", "all", money(100, 24), "profit", 7],
  ["Persistent Sellers", pandabuyAgent, money(1, 26), "profit", 9],
  ["Material Testers", sheinFactory, money(10, 26), "profit", 9],
  ["Lucky Brothers Group", wechat, money(20, 26), "profit", 9],
  ["Drone Cleaners", droneSwarm, money(100, 26), "profit", 9],
  ["Engagement Is A Drag", tiktokAlgo, money(200, 26), "profit", 9],
  ["Imperial Guards", huaweiPhone, money(400, 26), "profit", 9],
  ["Resistance Cohort", kimi, money(800, 26), "profit", 9],
  ["Doggie Hug Givers", robotDog, money(16, 27), "profit", 9],
  ["Bug Catchers", deepseek, money(222, 27), "profit", 9],
  ["Sacred Synergy", "all", money(666, 27), "profit", 9],
  ["China Rising", "all", money(1, 28), "profit", 9],
  ["Lucky Helping Hand", pandabuyAgent, money(2, 30), "profit", 15],
  ["Flame-Retardant Workers", sheinFactory, money(14, 30), "profit", 15],
  ["Got Your Group Chat", wechat, money(56, 30), "profit", 15],
  ["Good With Mesh Routing", droneSwarm, money(112, 30), "profit", 15],
  ["Still Not Privacy-Comfortable", tiktokAlgo, money(179, 30), "profit", 15],
  ["PR Secret Service", huaweiPhone, money(298, 30), "profit", 15],
  ["Idea Curators", kimi, money(434, 30), "profit", 15],
  ["Custom Skin Painters Guild", robotDog, money(620, 30), "profit", 15],
  ["Distillation Babysitters", deepseek, money(808, 30), "profit", 15],
  ["Here To Serve The People", "all", money(1, 31), "profit", 15],
  ["That Glorious Hour", "all", money(9, 33), "profit", 9],
  ["The Last Haul Upgrade", pandabuyAgent, money(34, 35), "profit", 21],
  ["The Last SKU Upgrade", sheinFactory, money(6, 35), "profit", 21],
  ["The Last Super App Upgrade", wechat, money(12, 35), "profit", 21],
  ["The Last Swarm Upgrade", droneSwarm, money(24, 35), "profit", 21],
  ["The Last FYP Upgrade", tiktokAlgo, money(69, 35), "profit", 21],
  ["The Last Diplomacy Upgrade", huaweiPhone, money(105, 35), "profit", 21],
  ["The Last Long-Context Upgrade", kimi, money(214, 35), "profit", 21],
  ["The Last Robot Dog Upgrade", robotDog, money(333, 35), "profit", 21],
  ["The Last DeepSeek Upgrade", deepseek, money(500, 35), "profit", 21],
  ["The End In Sight", "all", money(1, 36), "profit", 9],
  ["Praise The Party", "all", money(777, 37), "profit", 777],
];
