import type { BusinessId, ModifierKind, UpgradeTarget } from "./types";

type UpgradeRow = [string, UpgradeTarget, number, ModifierKind, number];

const money = (amount: number, tier: number) => amount * 10 ** (tier * 3);

const pandabuyAgent = "pandabuy-agent";
const sheinFactory = "shein-factory";
const wechat = "wechat";
const droneSwarm = "drone-swarm";
const tiktokAlgo = "tiktok-algo";
const huaweiPhone = "huawei-phone";
const kimi = "kimi";
const robotDog = "robot-dog";
const amdChip = "amd-chip";
const deepseek = "deepseek";

export const chinaBusinessIds = [
  pandabuyAgent,
  sheinFactory,
  wechat,
  droneSwarm,
  tiktokAlgo,
  huaweiPhone,
  kimi,
  robotDog,
  amdChip,
  deepseek,
] satisfies BusinessId[];

export const chinaCashUpgradeRows: UpgradeRow[] = [
  ["Shovel Extensions", pandabuyAgent, money(15, 2), "profit", 33],
  ["Oiler Oil", sheinFactory, money(500, 2), "profit", 33],
  ["Testosterone Cologne", wechat, money(100, 3), "profit", 33],
  ["Extra Tall Fences", droneSwarm, money(19, 4), "profit", 33],
  ["Warning Signs", tiktokAlgo, money(1, 5), "profit", 33],
  ["Interpretors", huaweiPhone, money(12, 6), "profit", 33],
  ["No Chafe Restraints", kimi, money(9, 7), "profit", 33],
  ["Free Me2 Album", robotDog, money(600, 7), "profit", 33],
  ["Genetic Modifications", deepseek, money(3, 9), "profit", 33],
  ["Plentiful BBQs", wechat, money(1, 11), "profit", 66],
  ["Saddles", droneSwarm, money(3, 12), "profit", 66],
  ["Spray Bottles", tiktokAlgo, money(25, 13), "profit", 66],
  ["Prepackaged Doves", huaweiPhone, money(130, 14), "profit", 66],
  ["Friendly Neuro-Scrubbers", kimi, money(300, 15), "profit", 66],
  ["Trendy Commercials", robotDog, money(60, 16), "profit", 66],
  ["Spider Treats", deepseek, money(10, 17), "profit", 66],
  ["O2 In A Can", "all", money(1, 18), "profit", 33],
  ["Fancy Wheelbarrows", pandabuyAgent, money(1, 19), "profit", 999],
  ["Cake Injections", sheinFactory, money(700, 19), "profit", 999],
  ["Video Games", wechat, money(900, 19), "profit", 99],
  ["Sugar Licks", droneSwarm, money(1, 20), "profit", 99],
  ["Brimstone Filters", tiktokAlgo, money(5, 21), "profit", 99],
  ["Olive Branches", huaweiPhone, money(17, 21), "profit", 99],
  ["Discount Uploads", kimi, money(99, 21), "profit", 99],
  ["Innovative Shapes", robotDog, money(231, 21), "profit", 99],
  ["Obedience Training", deepseek, money(333, 21), "profit", 99],
  ["Free Pretzels", "all", money(500, 22), "profit", 33],
  ["Work Gloves", pandabuyAgent, money(123, 23), "profit", 999],
  ["Super Sizers", sheinFactory, money(246, 23), "profit", 999],
  ["Milking Machines", droneSwarm, money(369, 23), "profit", 999],
  ["Fun Guns", huaweiPhone, money(2, 24), "profit", 999],
  ["Nose Implants", kimi, money(3, 24), "profit", 999],
  ["Oxygen Service Plans", robotDog, money(12, 24), "profit", 999],
  ["Spider Houses", deepseek, money(23, 24), "profit", 999],
  ["Novelty Bobbleheads", "all", money(1, 25), "profit", 66],
  ["Mullet Installer", pandabuyAgent, money(5, 33), "profit", 33],
  ["Splash Proof Friers", sheinFactory, money(125, 33), "profit", 33],
  ["BBQ Sauce Stocks", wechat, money(450, 33), "profit", 33],
  ["Squeeze Toys", droneSwarm, money(625, 33), "profit", 33],
  ["Friendship Invasion", huaweiPhone, money(3, 34), "profit", 33],
  ["Attractive Faux Spouses", kimi, money(25, 34), "profit", 33],
  ["New Charge Cables", robotDog, money(100, 34), "profit", 33],
  ["China Cars", "all", money(100, 35), "profit", 33],
  ["Big Ol' Buckets", pandabuyAgent, money(1, 36), "profit", 77],
  ["Mandatory Staff Sing Alongs", sheinFactory, money(4, 36), "profit", 77],
  ["Gunmetal Utensils", wechat, money(55, 36), "profit", 77],
  ["Buggle Drives", droneSwarm, money(90, 36), "profit", 77],
  ["Thoughtful Gifts", huaweiPhone, money(210, 36), "profit", 77],
  ["Inconspicous Turbans", kimi, money(431, 36), "profit", 77],
  ["Smile Lessons", robotDog, money(777, 36), "profit", 77],
  ["Lucky Stars", "all", money(500, 37), "profit", 777],
  ["Carbon Fiber Lassos", droneSwarm, money(5, 43), "profit", 33],
  ["Rainbows", huaweiPhone, money(35, 43), "profit", 33],
  ["Austrian Accent-er", kimi, money(177, 43), "profit", 33],
  ["Siriously Friendly AI", robotDog, money(569, 43), "profit", 33],
  ["Backhoe With Rockets", pandabuyAgent, money(714, 43), "profit", 33],
  ["Creamcheese Sprayer", sheinFactory, money(976, 43), "profit", 33],
  ["Rocket Golf Carts", wechat, money(1, 44), "profit", 33],
  ["Cheap Water", "all", money(50, 44), "profit", 33],
  ["Dump Tracks", pandabuyAgent, money(1, 47), "profit", 66],
  ["Smarmy Mascot", sheinFactory, money(2, 47), "profit", 66],
  ["Pirate Flags", wechat, money(6, 47), "profit", 66],
  ["Rodeo Clowns", droneSwarm, money(9, 47), "profit", 66],
  ["Ear Plugs", huaweiPhone, money(49, 47), "profit", 66],
  ["Robo-Taxi Upgrades", kimi, money(300, 47), "profit", 66],
  ["Free Tortoisenecks", robotDog, money(700, 47), "profit", 66],
  ["President Carter", "all", money(300, 48), "profit", 55],
  ["New Labels", pandabuyAgent, money(5, 51), "profit", 99],
  ["FDM Deregulation", sheinFactory, money(14, 51), "profit", 99],
  ["Military Hardware", wechat, money(66, 51), "profit", 99],
  ["Genetic Engineering", droneSwarm, money(88, 51), "profit", 99],
  ["Karaoke Machines", huaweiPhone, money(250, 51), "profit", 99],
  ["Mutant Slums", kimi, money(444, 51), "profit", 99],
  ["Fancy Logo", robotDog, money(653, 51), "profit", 99],
  ["Free Cookies", "all", money(1, 53), "profit", 15],
  ["Flashy Sandbags", pandabuyAgent, money(1, 56), "profit", 77],
  ["Shiny Bibs", sheinFactory, money(3, 56), "profit", 77],
  ["Carbon Nanotube Mugs", wechat, money(9, 56), "profit", 77],
  ["Fancy Feed", droneSwarm, money(19, 56), "profit", 77],
  ["Power Ties", huaweiPhone, money(36, 56), "profit", 77],
  ["Brain Drains", kimi, money(99, 56), "profit", 77],
  ["Magnetic Plugs", robotDog, money(279, 56), "profit", 77],
  ["Trees", "all", money(400, 56), "profit", 25],
  ["Anti-Grav Spades", pandabuyAgent, money(1, 60), "profit", 999],
  ["Sticks", sheinFactory, money(5, 60), "profit", 999],
  ["Lightning Shooters", wechat, money(8, 60), "profit", 999],
  ["Petting Zoo", droneSwarm, money(10, 60), "profit", 999],
  ["Sensitivity Training", huaweiPhone, money(66, 60), "profit", 999],
  ["Magnets", kimi, money(153, 60), "profit", 999],
  ["Is there life in Shenzhen?", robotDog, money(372, 60), "profit", 999],
  ["Test Spiders 11", deepseek, money(500, 60), "profit", 999],
  ["Regional Movers", pandabuyAgent, money(6, 66), "profit", 33],
  ["Beer-batter Formula", sheinFactory, money(25, 66), "profit", 33],
  ["Easy-On Muscles", wechat, money(80, 66), "profit", 33],
  ["Trusty Buggle-Dogs", droneSwarm, money(170, 66), "profit", 33],
  ["Diplomacy Simulators", huaweiPhone, money(439, 66), "profit", 33],
  ["$10 Rebate", kimi, money(650, 66), "profit", 33],
  ["More Marketing", robotDog, money(900, 66), "profit", 33],
  ["Big Old Lasers", deepseek, money(25, 67), "profit", 33],
  ["KLAATU Drones", "all", money(250, 67), "profit", 9],
  ["Dirt Magnets", pandabuyAgent, money(1, 70), "profit", 22],
  ["Mega Sized", sheinFactory, money(11, 70), "profit", 22],
  ["Micro-Breeds", droneSwarm, money(222, 70), "profit", 22],
  ["Elocution Lessons", huaweiPhone, money(333, 70), "profit", 22],
  ["A CHOPPA", kimi, money(444, 70), "profit", 22],
  ["Audience Engagwechatt", robotDog, money(555, 70), "profit", 22],
  ["Web Ornawechatts", deepseek, money(666, 70), "profit", 22],
  ["Magnetosphere", "all", money(1, 71), "profit", 66],
  ["All Terrain Scoopers", pandabuyAgent, money(10, 73), "profit", 44],
  ["Drone Delivery", sheinFactory, money(20, 73), "profit", 44],
  ["Funny Hats", droneSwarm, money(40, 73), "profit", 44],
  ["Revealing Robes", huaweiPhone, money(60, 73), "profit", 44],
  ["Good Lawyers", kimi, money(150, 73), "profit", 44],
  ["Hot Tubs", robotDog, money(356, 73), "profit", 44],
  ["Juicy Space Flies", deepseek, money(900, 73), "profit", 44],
  ["Market Independence", "all", money(6, 74), "profit", 777],
  ["The Mega Dirt Upgrade", pandabuyAgent, money(1, 75), "profit", 999],
  ["The Mega Marketplace Upgrade", sheinFactory, money(1, 76), "profit", 999],
  ["The Mega Buggle Upgrade", droneSwarm, money(1, 77), "profit", 999],
  ["The Mega Ambassador Upgrade", huaweiPhone, money(1, 78), "profit", 999],
  ["The Mega Brain-cation Upgrade", kimi, money(1, 79), "profit", 999],
  ["The Mega LiFE Pod Upgrade", robotDog, money(1, 80), "profit", 999],
  ["The Mega Terrorformer Upgrade", deepseek, money(1, 81), "profit", 999],
];

export const chinaAngelUpgradeRows: UpgradeRow[] = [
  ["Help From Above", "all", money(100, 3), "profit", 3],
  ["More Help From Above", "all", money(100, 5), "profit", 3],
  ["Holy Diggers", pandabuyAgent, money(1, 7), "profit", 5],
  ["Holy Friers", sheinFactory, money(2, 7), "profit", 5],
  ["Wingwechat", wechat, money(4, 7), "profit", 5],
  ["Holy Wranglers", droneSwarm, money(8, 7), "profit", 5],
  ["Conflict of Interest", tiktokAlgo, money(16, 7), "profit", 5],
  ["Holy Interpretors", huaweiPhone, money(32, 7), "profit", 5],
  ["Holy Implanters", kimi, money(64, 7), "profit", 5],
  ["Holy Camerawechat", robotDog, money(128, 7), "profit", 5],
  ["Holy Ranch Hands", deepseek, money(256, 7), "profit", 5],
  ["Holy Boosters", "all", money(1, 8), "profit", 3],
  ["Angelic Work Crew", pandabuyAgent, money(1, 10), "profit", 7],
  ["Consumers", sheinFactory, money(3, 10), "profit", 7],
  ["Fashion Consultants", wechat, money(9, 10), "profit", 7],
  ["Buggle Massagers", droneSwarm, money(27, 10), "profit", 7],
  ["Protal Guards", tiktokAlgo, money(100, 10), "profit", 7],
  ["Little Sandwich Servers", huaweiPhone, money(200, 10), "profit", 7],
  ["Disposable Henchwechat", kimi, money(400, 10), "profit", 7],
  ["Early Adopters", robotDog, money(600, 10), "profit", 7],
  ["Web Washers", deepseek, money(900, 10), "profit", 7],
  ["Delivery Angels", "all", money(1, 12), "profit", 5],
  ["Oxygen Wranglers", "all", money(1, 14), "profit", 3],
  ["Brushers", pandabuyAgent, money(3, 15), "profit", 3],
  ["Graceful Cashiers", sheinFactory, money(12, 15), "profit", 3],
  ["Palm Leaf Fanners", wechat, money(29, 15), "profit", 3],
  ["Buggle Pokes", droneSwarm, money(136, 15), "profit", 3],
  ["If You Say So", tiktokAlgo, money(311, 15), "profit", 3],
  ["Dignitary Chaffeurs", huaweiPhone, money(555, 15), "profit", 3],
  ["Nurses", kimi, money(789, 15), "profit", 3],
  ["Pod Installers", robotDog, money(25, 16), "profit", 3],
  ["Terrorformer Bait", deepseek, money(100, 16), "profit", 3],
  ["Wandering Saleswechat", "all", money(100, 18), "profit", 5],
  ["Dirt Quality Assurance", pandabuyAgent, money(1, 20), "profit", 5],
  ["Chocolate Injectors", sheinFactory, money(5, 20), "profit", 5],
  ["Landlords", wechat, money(45, 20), "profit", 5],
  ["Buggle Milkers", droneSwarm, money(66, 20), "profit", 5],
  ["Containwechatt Units", tiktokAlgo, money(99, 20), "profit", 5],
  ["Secret Spies", huaweiPhone, money(175, 20), "profit", 5],
  ["Brain Fixers", kimi, money(280, 20), "profit", 5],
  ["Pod People", robotDog, money(420, 20), "profit", 5],
  ["Atmosphere Testers", deepseek, money(700, 20), "profit", 5],
  ["China Angel, Will You Be Mine", "all", money(5, 21), "profit", 5],
  ["Holy Hotpot", "all", money(100, 24), "profit", 7],
  ["Keeping On", pandabuyAgent, money(1, 26), "profit", 9],
  ["Food Testers", sheinFactory, money(10, 26), "profit", 9],
  ["Holy Bros", wechat, money(20, 26), "profit", 9],
  ["Buggle Washers", droneSwarm, money(100, 26), "profit", 9],
  ["Heck Is A Heck Of A Drag", tiktokAlgo, money(200, 26), "profit", 9],
  ["Body Guards", huaweiPhone, money(400, 26), "profit", 9],
  ["Resistance Members", kimi, money(800, 26), "profit", 9],
  ["Hug Givers", robotDog, money(16, 27), "profit", 9],
  ["Fly Catchers", deepseek, money(222, 27), "profit", 9],
  ["Holy Synergy", "all", money(666, 27), "profit", 9],
  ["China Rising", "all", money(1, 28), "profit", 9],
  ["Helpful Hand", pandabuyAgent, money(2, 30), "profit", 15],
  ["Burn Proof Workers", sheinFactory, money(14, 30), "profit", 15],
  ["Got Your Back", wechat, money(56, 30), "profit", 15],
  ["Good With Animals", droneSwarm, money(112, 30), "profit", 15],
  ["Still Not Comfortable", tiktokAlgo, money(179, 30), "profit", 15],
  ["Secret Service", huaweiPhone, money(298, 30), "profit", 15],
  ["Idea Men", kimi, money(434, 30), "profit", 15],
  ["Pod Decorators", robotDog, money(620, 30), "profit", 15],
  ["Baby Sitters", deepseek, money(808, 30), "profit", 15],
  ["Here To Serve", "all", money(1, 31), "profit", 15],
  ["That Glorious Hour", "all", money(9, 33), "profit", 9],
  ["The Last Dirt Upgrade", pandabuyAgent, money(34, 35), "profit", 21],
  ["The Last Marketplace Upgrade", sheinFactory, money(6, 35), "profit", 21],
  ["The Last Manly Upgrade", wechat, money(12, 35), "profit", 21],
  ["The Last Buggle Upgrade", droneSwarm, money(24, 35), "profit", 21],
  ["The Last Heck Upgrade", tiktokAlgo, money(69, 35), "profit", 21],
  ["The Last Ambassador Upgrade", huaweiPhone, money(105, 35), "profit", 21],
  ["The Last Brain Upgrade", kimi, money(214, 35), "profit", 21],
  ["The Last LiFE Pod Upgrade", robotDog, money(333, 35), "profit", 21],
  ["The Last Terrorformer Upgrade", deepseek, money(500, 35), "profit", 21],
  ["The End In Sight", "all", money(1, 36), "profit", 9],
  ["Praise Ares", "all", money(777, 37), "profit", 777],
];
