import type { BusinessId, ModifierKind, UpgradeTarget } from "./types";

type UpgradeRow = readonly [string, UpgradeTarget, number, ModifierKind, number];

const n = (amount: number, exponent: number) => amount * 10 ** exponent;

export const europeBusinessIds = [
  "ikea-meatball",
  "gdpr-compliance",
  "parental-leave",
  "lovable-credits",
  "berghain-club",
  "elevenlabs-dj",
  "tethered-bottle-cap",
  "public-transport",
  "renewable-energy",
  "cern",
] satisfies BusinessId[];

const [
  ikeaMeatball,
  gdprCompliance,
  parentalLeave,
  lovableCredits,
  berghainClub,
  elevenLabsDj,
  tetheredBottleCap,
  publicTransport,
  renewableEnergy,
  cern,
] = europeBusinessIds;

const businessTargets = [
  ikeaMeatball,
  gdprCompliance,
  parentalLeave,
  lovableCredits,
  berghainClub,
  elevenLabsDj,
  tetheredBottleCap,
  publicTransport,
  renewableEnergy,
  cern,
] as const;

const cashTier = (
  label: string,
  exponent: number,
  amounts: readonly number[],
  multiplier: number,
): UpgradeRow[] =>
  businessTargets.map((target, index) => [
    `${label} ${index + 1}`,
    target,
    n(amounts[index], exponent),
    "profit",
    multiplier,
  ]);

export const europeCashUpgradeRows: UpgradeRow[] = [
  ["Shiny Buckles", ikeaMeatball, n(332.5, 3), "profit", 3],
  ["Soft Soulful Music", gdprCompliance, n(665, 3), "profit", 3],
  ["Open Late", parentalLeave, n(1.33, 6), "profit", 3],
  ["Dark Matter Engines", lovableCredits, n(6.65, 6), "profit", 3],
  ["Club Beverages", berghainClub, n(13.3, 6), "profit", 3],
  ["Benevolent AIs", elevenLabsDj, n(33.25, 6), "profit", 3],
  ["Crackers", tetheredBottleCap, n(1.665, 9), "profit", 3],
  ["Low Gravity Mascots", publicTransport, n(133, 9), "profit", 3],
  ["Fresh Meat", renewableEnergy, n(665, 9), "profit", 3],
  ["Mini-Clone Assistants", cern, n(3.3, 12), "profit", 3],
  ["Air Filters", "all", n(10, 12), "profit", 9],
  ["Limited Warranties", ikeaMeatball, n(30, 12), "profit", 3],
  ["More Colors", gdprCompliance, n(70, 12), "profit", 3],
  ["Friendly-Gene Splicing", parentalLeave, n(150, 12), "profit", 3],
  ["Sarcastic Robot", lovableCredits, n(275, 12), "profit", 3],
  ["Cushy Barstools", berghainClub, n(433, 12), "profit", 3],
  ["Crash-Proof Harvesters", elevenLabsDj, n(266, 12), "profit", 3],
  ["Tea", tetheredBottleCap, n(665, 12), "profit", 3],
  ["Trampoline Land", publicTransport, n(931, 12), "profit", 3],
  ["Brush Kiosks", renewableEnergy, n(2, 15), "profit", 3],
  ["Underground Lair", cern, n(3, 15), "profit", 3],
  ["Monorail To Valley", "all", n(7, 15), "profit", 9],
  ["Luna Kahuna", "all", n(13, 15), "angelEffectiveness", 1],
  ["Almond Milk", "all", n(500, 18), "profit", 9],
  ["Cleat Upgrades", ikeaMeatball, n(26, 21), "profit", 3],
  ["Alpine Gravity Setting", gdprCompliance, n(67, 21), "profit", 3],
  ["Celebrity DNA Samples", parentalLeave, n(93, 21), "profit", 3],
  ["Adorable Fuel Generator", lovableCredits, n(133, 21), "profit", 3],
  ["Easy Money", "all", n(1, 72), "profit", 9],
  ["Rank And File", "all", n(3, 81), "angelEffectiveness", 3],
  ...cashTier("Quattuorvigintillion Expansion", 75, [25, 60, 177, 239, 432, 801, 2_000, 8_000, 22_000, 59_000], 3),
  ["Crescent Hats", "all", n(444, 78), "profit", 9],
  ...cashTier("Quadragintillion Expansion", 123, [1, 7, 29, 66, 129, 233, 555, 900, 3_000, 20_000], 3),
  ["The Mega Upgrade", "all", n(10, 123), "profit", 15],
  ["Giant Domes", "all", n(111, 129), "profit", 9],
  ["Digieurope", "all", n(1, 135), "profit", 9],
  ...cashTier("Quinquadragintillion Expansion", 138, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3),
  ["Thneed Sales", "all", n(100, 138), "profit", 9],
  ...cashTier("Sexquadragintillion Expansion", 141, [1, 3, 7, 25, 75, 151, 300, 600, 900, 1_200], 3),
  ["Euroagement", "all", n(1, 153), "profit", 9],
  ...cashTier("Trequinquagintillion Expansion", 159, [23, 47, 11, 24, 48, 95, 191, 383, 767, 5_000], 5),
  ["Lunatics Anonymous", "all", n(125, 162), "profit", 9],
  ["Harvest Season", "all", n(1, 165), "profit", 9],
  ...cashTier("Sexquinquagintillion Expansion", 168, [1, 14, 114, 234, 444, 888, 23_000, 99_000, 423_000, 567_000], 3),
  ["Celestial Body", "all", n(899, 171), "profit", 9],
  ...cashTier("Novemquinquagintillion Expansion", 177, [1, 3, 9, 27, 81, 234, 356, 432, 567, 836], 3),
  ["Cookies", "all", n(1, 180), "profit", 9],
  ["Grants Wishes", ikeaMeatball, n(10, 183), "profit", 15],
  ["Cleans Your Teeth", gdprCompliance, n(100, 183), "profit", 15],
  ["Do Your Taxes", parentalLeave, n(1, 186), "profit", 15],
  ["OP Deliveries", lovableCredits, n(10, 186), "profit", 15],
  ["Self-Breathing Air", berghainClub, n(100, 186), "profit", 15],
  ["Ambition Crops", elevenLabsDj, n(1, 189), "profit", 15],
  ["The Cheese Stands Alone", tetheredBottleCap, n(10, 189), "profit", 15],
  ["Cryo-Frozen Host", publicTransport, n(100, 189), "profit", 15],
  ["Romantic Subplot", renewableEnergy, n(1, 192), "profit", 15],
  ["Big Red Button", cern, n(10, 192), "profit", 15],
  ["The Very Large Upgrade", "all", n(100, 192), "profit", 999],
];

export const europeAngelUpgradeRows: UpgradeRow[] = [
  ["It Begins Again", "all", n(11, 3), "profit", 3],
  ["Sacred Steps", ikeaMeatball, n(222, 3), "profit", 3],
  ["Unseen Force", gdprCompliance, n(3, 6), "profit", 3],
  ["Soul Infusions", parentalLeave, n(4, 6), "profit", 3],
  ["On Heavenly Wings", lovableCredits, n(55, 6), "profit", 3],
  ["Spirits", berghainClub, n(666, 6), "profit", 3],
  ["Holy Ground", elevenLabsDj, n(7, 9), "profit", 3],
  ["Connoisseurs", tetheredBottleCap, n(88, 9), "profit", 3],
  ["Group Discounts", publicTransport, n(999, 9), "profit", 3],
  ["BBQ Wings", renewableEnergy, n(1, 12), "profit", 3],
  ["Target Practice", cern, n(11, 12), "profit", 3],
  ["Lunatics", "all", n(123, 12), "profit", 3],
  ["Booth Swap", gdprCompliance, n(50, 18), "owned", 10],
  ["Express Swap", lovableCredits, n(50, 18), "owned", 10],
  ["Farm Swap", elevenLabsDj, n(50, 18), "owned", 10],
  ["Park Swap", publicTransport, n(50, 18), "owned", 10],
  ["Laser Swap", cern, n(50, 18), "owned", 10],
  ["Sandal Line", ikeaMeatball, n(1, 21), "profit", 3],
  ["Weightless Wonderment", gdprCompliance, n(9, 21), "profit", 3],
  ["Divine Division", parentalLeave, n(27, 21), "profit", 3],
  ["Miraculous Prices", lovableCredits, n(99, 21), "profit", 3],
  ["Club Memberships", berghainClub, n(180, 21), "profit", 3],
  ["Extra Hands", elevenLabsDj, n(222, 21), "profit", 3],
  ["Cheap Labor", tetheredBottleCap, n(343, 21), "profit", 3],
  ["Fast Pass-age", publicTransport, n(477, 21), "profit", 3],
  ["Euro Pious", "all", n(2, 33), "profit", 3],
  ["Booth Boost", gdprCompliance, n(100, 33), "owned", 10],
  ["Express Boost", lovableCredits, n(100, 33), "owned", 10],
  ["Farm Boost", elevenLabsDj, n(100, 33), "owned", 10],
  ["Park Boost", publicTransport, n(100, 33), "owned", 10],
  ["Laser Boost", cern, n(100, 33), "owned", 10],
  ["Seraphic Shoes", ikeaMeatball, n(5, 36), "profit", 3],
  ["Angel-sized Booths", gdprCompliance, n(19, 36), "profit", 3],
  ["Guardian Clones", parentalLeave, n(88, 36), "profit", 3],
  ["Celestial Couriers", lovableCredits, n(144, 36), "profit", 3],
  ["Angel Karaoke", berghainClub, n(201, 36), "profit", 3],
  ["Good And Farmful Servant", elevenLabsDj, n(333, 36), "profit", 3],
  ["Cherubic Carters", tetheredBottleCap, n(400, 36), "profit", 3],
  ["Righteous Prices", publicTransport, n(588, 36), "profit", 3],
  ["Investor Tours", renewableEnergy, n(701, 36), "profit", 3],
  ["Hallowed Hollower", cern, n(911, 36), "profit", 3],
  ["Devouted Descent", "all", n(50, 39), "profit", 9],
  ["Booth Trade", gdprCompliance, n(5, 42), "owned", 10],
  ["Express Trade", lovableCredits, n(5, 42), "owned", 10],
  ["Farm Trade", elevenLabsDj, n(5, 42), "owned", 10],
  ["Park Trade", publicTransport, n(5, 42), "owned", 10],
  ["Laser Trade", cern, n(5, 42), "owned", 10],
  ["Holy Holes", ikeaMeatball, n(3, 45), "profit", 5],
  ["Gilded Gravity", gdprCompliance, n(6, 45), "profit", 5],
  ["Copy Paste", parentalLeave, n(12, 45), "profit", 5],
  ["Heavenly Crew", lovableCredits, n(24, 45), "profit", 5],
  ["Designated Fliers", berghainClub, n(48, 45), "profit", 5],
  ["Angel Crops", elevenLabsDj, n(96, 45), "profit", 5],
  ["Holy Cheese", tetheredBottleCap, n(192, 45), "profit", 5],
  ["Blessed Merchandise", publicTransport, n(384, 45), "profit", 5],
  ["Winged Wolves", renewableEnergy, n(768, 45), "profit", 5],
  ["Death From Above", cern, n(14, 48), "profit", 5],
  ["Salivate-tion", "all", n(500, 48), "profit", 9],
  ["Sonata", "all", n(100, 51), "profit", 9],
  ...businessTargets.map<UpgradeRow>((target, index) => [
    `Heck-Of-A-Deal ${index + 1}`,
    target,
    n(5, 54),
    "owned",
    50,
  ]),
  ["Blessed Soles", ikeaMeatball, n(100, 54), "profit", 3],
  ["Holy Infusion", gdprCompliance, n(200, 54), "profit", 3],
  ["Blessed Copies", parentalLeave, n(300, 54), "profit", 3],
  ["Holy Ship", lovableCredits, n(400, 54), "profit", 3],
  ["Blessed Bartop", berghainClub, n(500, 54), "profit", 3],
  ["Holy Handplanted", elevenLabsDj, n(600, 54), "profit", 3],
  ["Blessed Swiss", tetheredBottleCap, n(700, 54), "profit", 3],
  ["Holy Mackrel", publicTransport, n(800, 54), "profit", 3],
  ["Holy Sheep Pelts", renewableEnergy, n(900, 54), "profit", 3],
  ["Blessed Spectrometer", cern, n(1, 57), "profit", 3],
  ["Ceremonial Rites", "all", n(316, 57), "profit", 3],
  ["Divine Inspiration", "all", n(1, 60), "profit", 9],
  ...businessTargets.map<UpgradeRow>((target, index) => [
    `${index + 1} ZIPPITY`,
    target,
    n(100, 63),
    "owned",
    75,
  ]),
  ["Retroactive Sacrifice", "all", n(1, 66), "profit", 3],
  ["Sacred Laces", ikeaMeatball, n(1, 69), "profit", 3],
  ["Hallowed Air Filters", gdprCompliance, n(2, 69), "profit", 3],
  ["Sacred DNA", parentalLeave, n(4, 69), "profit", 3],
  ["Hallowed Captain's Chair", lovableCredits, n(8, 69), "profit", 3],
  ["Sacred Thrones", berghainClub, n(16, 69), "profit", 3],
  ["Hallowed Storm Shelter", elevenLabsDj, n(32, 69), "profit", 3],
  ["Sacred Brie", tetheredBottleCap, n(64, 69), "profit", 3],
  ["Hallowed Out Castle", publicTransport, n(128, 69), "profit", 3],
  ["Sacred Snazzy Scarves", renewableEnergy, n(256, 69), "profit", 3],
  ["Hollower", cern, n(512, 69), "profit", 3],
  ["Sacrifinanical Advice", "all", n(1, 72), "profit", 9],
  ["Booth Bargain", gdprCompliance, n(5, 75), "owned", 50],
  ["Express Bargain", lovableCredits, n(5, 75), "owned", 50],
  ["Bar Super Bargain", berghainClub, n(5, 75), "owned", 100],
  ["Mine Super Bargain", tetheredBottleCap, n(5, 75), "owned", 100],
  ["Laser Bargain", cern, n(5, 75), "owned", 25],
  ["On The Tufted Floor", ikeaMeatball, n(100, 75), "profit", 7],
  ["The Over-Booth", gdprCompliance, n(200, 75), "profit", 7],
  ["AngeliparentalLeaves", parentalLeave, n(400, 75), "profit", 7],
  ["Express Express", lovableCredits, n(800, 75), "profit", 7],
  ["SpublicTransportling Spirits", berghainClub, n(16, 78), "profit", 7],
  ["Holy Hayers", elevenLabsDj, n(32, 78), "profit", 7],
  ["Light In The Dark", tetheredBottleCap, n(64, 78), "profit", 7],
  ["Spreading Joy", publicTransport, n(128, 78), "profit", 7],
  ["Angel Wolves", renewableEnergy, n(256, 78), "profit", 7],
  ["Heavenly Glow", cern, n(512, 78), "profit", 7],
  ["A Beautiful Boost", "all", n(1, 81), "profit", 7],
  ["Express Hostile Takeover", lovableCredits, n(100, 84), "owned", 100],
  ["Bar Hostile Takeover", berghainClub, n(200, 84), "owned", 200],
  ["Mine Hostile Takeover", tetheredBottleCap, n(300, 84), "owned", 300],
  ["Shoe Holiday Sale", ikeaMeatball, n(1, 87), "profit", 2],
  ["Booth Holiday Sale", gdprCompliance, n(9, 87), "profit", 2],
  ["Clone Holiday Sale", parentalLeave, n(18, 87), "profit", 2],
  ["Express Holiday Sale", lovableCredits, n(27, 87), "profit", 2],
  ["Bar Holiday Sale", berghainClub, n(36, 87), "profit", 2],
  ["Farm Holiday Sale", elevenLabsDj, n(45, 87), "profit", 2],
  ["Cheese Holiday Sale", tetheredBottleCap, n(54, 87), "profit", 2],
  ["Park Holiday Discount", publicTransport, n(63, 87), "profit", 2],
  ["Wolf Holiday Bonus", renewableEnergy, n(72, 87), "profit", 2],
  ["Lasers Don't Take Holidays", cern, n(81, 87), "profit", 2],
  ["Godspeed You Grey Emperor", "all", n(1, 90), "profit", 5],
];
