import type { BusinessId, ModifierKind, UpgradeTarget } from "./types";

type UpgradeRow = readonly [string, UpgradeTarget, number, ModifierKind, number];

const n = (amount: number, exponent: number) => amount * 10 ** exponent;

export const europeBusinessIds = [
  "ikea-meatball",
  "gdpr-compliance",
  "parental-leave",
  "lovable-credits",
  "berghain-club",
  "elevenlabs-dj",
  "tethered-bottle-cap",
  "public-transport",
  "renewable-energy",
  "cern",
] satisfies BusinessId[];

const [
  ikeaMeatball,
  gdprCompliance,
  parentalLeave,
  lovableCredits,
  berghainClub,
  elevenLabsDj,
  tetheredBottleCap,
  publicTransport,
  renewableEnergy,
  cern,
] = europeBusinessIds;

export const europeCashUpgradeRows: UpgradeRow[] = [
  ["Lingonberry Glaze", ikeaMeatball, n(332.5, 3), "profit", 3],
  ["Cookie Consent Banner", gdprCompliance, n(665, 3), "profit", 3],
  ["13th Month Bonus", parentalLeave, n(1.33, 6), "profit", 3],
  ["Prompt Autocomplete", lovableCredits, n(6.65, 6), "profit", 3],
  ["House Beer Discount", berghainClub, n(13.3, 6), "profit", 3],
  ["Audiobook Narrator Pack", elevenLabsDj, n(33.25, 6), "profit", 3],
  ["Crackle-Proof Plastic", tetheredBottleCap, n(1.665, 9), "profit", 3],
  ["Friendly Conductors", publicTransport, n(133, 9), "profit", 3],
  ["Fresh Wind Currents", renewableEnergy, n(665, 9), "profit", 3],
  ["Junior Researcher Cohort", cern, n(3.3, 12), "profit", 3],
  ["Clean Air Mandate", "all", n(10, 12), "profit", 9],
  ["Two-Year Warranty Stretch", ikeaMeatball, n(30, 12), "profit", 3],
  ["Nicobox.se", gdprCompliance, n(57, 12), "profit", 3],
  ["Friendly HR Policies", parentalLeave, n(150, 12), "profit", 3],
  ["Sarcastic Code Reviewer", lovableCredits, n(275, 12), "profit", 3],
  ["Plush Backroom Sofas", berghainClub, n(433, 12), "profit", 3],
  ["Crash-Proof Render Farm", elevenLabsDj, n(266, 12), "profit", 3],
  ["Tea-Bottle Variant", tetheredBottleCap, n(665, 12), "profit", 3],
  ["Bouncy Tram Suspension", publicTransport, n(931, 12), "profit", 3],
  ["Brush Turbine Maintenance", renewableEnergy, n(2, 15), "profit", 3],
  ["Underground Tunnel Lair", cern, n(3, 15), "profit", 3],
  ["High-Speed Rail to Valley", "all", n(7, 15), "profit", 9],
  ["Brussels Kahuna", "all", n(13, 15), "angelEffectiveness", 1],
  ["Almondmilk Subsidy", "all", n(500, 18), "profit", 9],
  ["Cleat-Mounted Plates", ikeaMeatball, n(26, 21), "profit", 3],
  ["Lagom Phone", gdprCompliance, n(22, 21), "profit", 3],
  ["Celebrity Endorsement Leave", parentalLeave, n(93, 21), "profit", 3],
  ["Adorable Component Library", lovableCredits, n(133, 21), "profit", 3],
  ["Bottle Service Lounges", berghainClub, n(266, 21), "profit", 3],
  ["Holographic Hype Man", elevenLabsDj, n(465, 21), "profit", 3],
  ["Color-Matched Tethers", tetheredBottleCap, n(665, 21), "profit", 3],
  ["Free Public Wifi", publicTransport, n(997, 21), "profit", 3],
  ["Offshore Wind Spiral", renewableEnergy, n(2, 24), "profit", 3],
  ["Hadron Hum", cern, n(3, 24), "profit", 3],
  ["Schengen Effect", "all", n(10, 24), "profit", 9],
  ["Brussels Blessing", "all", n(20, 24), "angelEffectiveness", 1],
  ["Anti-Splash Tray", ikeaMeatball, n(5, 30), "profit", 3],
  ["Cookie Banner Maximalism", gdprCompliance, n(10, 30), "profit", 3],
  ["Extended Paternity Window", parentalLeave, n(20, 30), "profit", 3],
  ["Tab Auto-Complete", lovableCredits, n(40, 30), "profit", 3],
  ["Industrial Strobes", berghainClub, n(160, 30), "profit", 3],
  ["Multilingual Vocals", elevenLabsDj, n(280, 30), "profit", 3],
  ["Color-Coded Bottle Caps", tetheredBottleCap, n(500, 30), "profit", 3],
  ["Late-Night Trams", publicTransport, n(690, 30), "profit", 3],
  ["Offshore Wind Farms", renewableEnergy, n(725, 30), "profit", 3],
  ["Magnet Cooling System", cern, n(833, 30), "profit", 3],
  ["Eurovision Halftime Show", "all", n(975, 30), "profit", 9],
  ["ECB Lifeline", "all", n(4, 33), "angelEffectiveness", 1],
  ["Bulk Pack Discounts", ikeaMeatball, n(9, 33), "profit", 3],
  ["Subject Access Requests", gdprCompliance, n(20, 33), "profit", 3],
  ["Sabbatical Programs", parentalLeave, n(100, 33), "profit", 3],
  ["Vibe-Coded Apps", lovableCredits, n(200, 33), "profit", 3],
  ["Backroom Lounges", berghainClub, n(421, 33), "profit", 3],
  ["Synthetic DJ Sets", elevenLabsDj, n(655, 33), "profit", 3],
  ["Mandatory Tethering", tetheredBottleCap, n(825, 33), "profit", 3],
  ["High-Speed Rail Network", publicTransport, n(5, 36), "profit", 3],
  ["Carbon-Negative Plants", renewableEnergy, n(25, 36), "profit", 3],
  ["Higgs Boson Re-Discovery", cern, n(50, 36), "profit", 3],
  ["Single Market Doctrine", "all", n(100, 36), "profit", 9],
  ["Self-Assembling Furniture", ikeaMeatball, n(75, 39), "profit", 5],
  ["Right To Be Forgotten", gdprCompliance, n(210, 39), "profit", 5],
  ["Four-Day Work Week", parentalLeave, n(353, 39), "profit", 5],
  ["One-Shot Deployments", lovableCredits, n(635, 39), "profit", 5],
  ["VIP Smoking Room", berghainClub, n(900, 39), "profit", 5],
  ["Voice Cloning Demo", elevenLabsDj, n(9, 42), "profit", 5],
  ["Recycling Loop Compliance", tetheredBottleCap, n(22, 42), "profit", 5],
  ["Metro Wifi Everywhere", publicTransport, n(60, 42), "profit", 5],
  ["Solar Roof Mandate", renewableEnergy, n(132, 42), "profit", 5],
  ["Antimatter Storage", cern, n(367, 42), "profit", 5],
  ["GI Protected Status", "all", n(1, 45), "profit", 9],
  ["Treaty Of Lisbon Update", "all", n(1, 51), "profit", 9],
  ["Patron Saint Stipend", "all", n(1, 54), "angelEffectiveness", 3],
  ["Stitched Tablecloth", ikeaMeatball, n(18, 54), "profit", 3],
  ["Encryption Mandate", gdprCompliance, n(6, 54), "profit", 3],
  ["Universal Childcare", parentalLeave, n(79, 54), "profit", 3],
  ["AI Code Reviewer", lovableCredits, n(110, 54), "profit", 3],
  ["All-Night Permits", berghainClub, n(220, 54), "profit", 3],
  ["Hyper-Real Sample Pack", elevenLabsDj, n(399, 54), "profit", 3],
  ["Single-Use Plastic Ban", tetheredBottleCap, n(666, 54), "profit", 3],
  ["Eurail Mega Pass", publicTransport, n(911, 54), "profit", 3],
  ["Tidal Energy Arrays", renewableEnergy, n(4, 60), "profit", 3],
  ["Linear Collider Upgrade", cern, n(25, 60), "profit", 3],
  ["Pan-European Holiday", "all", n(112, 60), "profit", 9],
  ["Cinnamon Bun Sidecar", ikeaMeatball, n(200, 60), "profit", 3],
  ["Privacy By Design", gdprCompliance, n(356, 60), "profit", 3],
  ["Paid Sabbaticals", parentalLeave, n(518, 60), "profit", 3],
  ["Atomic UI Generator", lovableCredits, n(766, 60), "profit", 3],
  ["Curated Door Policy", berghainClub, n(3, 69), "profit", 3],
  ["Custom Voice Models", elevenLabsDj, n(6, 69), "profit", 3],
  ["Cap-Cap Auto Pour", tetheredBottleCap, n(12, 69), "profit", 3],
  ["Driverless Trams", publicTransport, n(50, 69), "profit", 3],
  ["Geothermal Wells", renewableEnergy, n(212, 69), "profit", 3],
  ["Quantum Detector Array", cern, n(367, 69), "profit", 3],
  ["Easy Money", "all", n(1, 72), "profit", 9],
  ["Bureaucratic Hierarchy", "all", n(3, 81), "angelEffectiveness", 3],
  ["Allen Key Reinforcement", ikeaMeatball, n(25, 75), "profit", 3],
  ["Privacy Officer Council", gdprCompliance, n(60, 75), "profit", 3],
  ["Sabbatical Year Program", parentalLeave, n(177, 75), "profit", 3],
  ["Cross-Browser Polish", lovableCredits, n(239, 75), "profit", 3],
  ["Underground Speaker Stack", berghainClub, n(432, 75), "profit", 3],
  ["Diphone Library Cache", elevenLabsDj, n(801, 75), "profit", 3],
  ["Tamper Audit Trail", tetheredBottleCap, n(2000, 75), "profit", 3],
  ["Schengen Express Routes", publicTransport, n(8000, 75), "profit", 3],
  ["Floating Wind Farms", renewableEnergy, n(22000, 75), "profit", 3],
  ["Beam Splitter Refit", cern, n(59000, 75), "profit", 3],
  ["Crescent Hats", "all", n(444, 78), "profit", 9],
  ["Anti-Static Coasters", ikeaMeatball, n(12, 84), "profit", 3],
  ["Auto-Generated Privacy Policies", gdprCompliance, n(24, 84), "profit", 3],
  ["Wellbeing Mandates", parentalLeave, n(48, 84), "profit", 3],
  ["Hot Reload Everything", lovableCredits, n(96, 84), "profit", 3],
  ["Cloakroom Concierge", berghainClub, n(192, 84), "profit", 3],
  ["Emotion-Tuned Vocals", elevenLabsDj, n(384, 84), "profit", 3],
  ["Tamper-Evident Seals", tetheredBottleCap, n(968, 84), "profit", 3],
  ["Sleeper Train Network", publicTransport, n(15, 87), "profit", 3],
  ["Hydrogen Pipeline", renewableEnergy, n(35, 87), "profit", 3],
  ["Beam Steering Magnets", cern, n(100, 87), "profit", 3],
  ["Erasmus For Everyone", "all", n(1, 90), "profit", 9],
  ["Limited Edition Gloegg", ikeaMeatball, n(100, 90), "profit", 5],
  ["Pseudonymization Layer", gdprCompliance, n(200, 90), "profit", 5],
  ["Tenure Track", parentalLeave, n(300, 90), "profit", 5],
  ["Edge Function Workers", lovableCredits, n(400, 90), "profit", 5],
  ["Door Whisper Network", berghainClub, n(500, 90), "profit", 5],
  ["Singing Synthetic Idols", elevenLabsDj, n(600, 90), "profit", 5],
  ["Cap Adhesion Audits", tetheredBottleCap, n(700, 90), "profit", 5],
  ["Hyperloop Pilot Lines", publicTransport, n(800, 90), "profit", 5],
  ["Fusion Pilot Plants", renewableEnergy, n(900, 90), "profit", 5],
  ["Strangelet Lab", cern, n(999, 90), "profit", 5],
  ["Europa Mania", "all", n(5, 93), "profit", 9],
  ["Cardamom Variety", ikeaMeatball, n(10, 93), "profit", 3],
  ["Consent Without Fatigue", gdprCompliance, n(20, 93), "profit", 3],
  ["Daycare On Premise", parentalLeave, n(55, 93), "profit", 3],
  ["Auto-Saved Prompts", lovableCredits, n(90, 93), "profit", 3],
  ["Dance Floor Cosmos", berghainClub, n(180, 93), "profit", 3],
  ["Polyglot Audiobooks", elevenLabsDj, n(400, 93), "profit", 3],
  ["Tether Engineering Grant", tetheredBottleCap, n(750, 93), "profit", 3],
  ["Festival Pass Bundle", publicTransport, n(2, 96), "profit", 3],
  ["Smart Grid Mesh", renewableEnergy, n(4, 96), "profit", 3],
  ["More Antiprotons", cern, n(14, 96), "profit", 3],
  ["EU Earth Day", "all", n(50, 96), "profit", 9],
  ["Designer Linen Napkins", ikeaMeatball, n(400, 96), "profit", 3],
  ["Data Sovereignty Pacts", gdprCompliance, n(700, 96), "profit", 3],
  ["Grandparent Leave", parentalLeave, n(1, 99), "profit", 3],
  ["Discount Vibe Tokens", lovableCredits, n(3, 99), "profit", 3],
  ["Six-Hour Set Times", berghainClub, n(19, 99), "profit", 3],
  ["Karaoke-Quality AI", elevenLabsDj, n(55, 99), "profit", 3],
  ["Microplastic Trackers", tetheredBottleCap, n(123, 99), "profit", 3],
  ["Toddler Tram Tickets", publicTransport, n(200, 99), "profit", 3],
  ["Pumped Storage Arrays", renewableEnergy, n(600, 99), "profit", 3],
  ["Beam Dump Redundancy", cern, n(888, 99), "profit", 3],
  ["EU Hats For All", "all", n(1, 102), "profit", 9],
  ["Now In Charcoal", ikeaMeatball, n(5, 102), "profit", 3],
  ["Accessible By Design", gdprCompliance, n(25, 102), "profit", 3],
  ["Family Allowance App", parentalLeave, n(125, 102), "profit", 3],
  ["Captain's Prompt", lovableCredits, n(625, 102), "profit", 3],
  ["Smoke Machine Encore", berghainClub, n(3, 105), "profit", 3],
  ["Choir Of Replicas", elevenLabsDj, n(5, 105), "profit", 3],
  ["Espresso-Powered Caps", tetheredBottleCap, n(65, 105), "profit", 3],
  ["Sister City Pact", publicTransport, n(246, 105), "profit", 3],
  ["Discount Carbon Credits", renewableEnergy, n(500, 105), "profit", 3],
  ["Recycled Photons", cern, n(808, 105), "profit", 3],
  ["Pep Talks", "all", n(1, 108), "profit", 9],
  ["Air Almonds", ikeaMeatball, n(2, 108), "profit", 3],
  ["Free Lawyer Consults", gdprCompliance, n(4, 108), "profit", 3],
  ["Open 365 Days", parentalLeave, n(8, 108), "profit", 3],
  ["New Skin Themes", lovableCredits, n(16, 108), "profit", 3],
  ["Conversation Pits", berghainClub, n(32, 108), "profit", 3],
  ["Total Catalog Mastery", elevenLabsDj, n(64, 108), "profit", 3],
  ["Cap Refiners", tetheredBottleCap, n(128, 108), "profit", 3],
  ["Loompa Conductors", publicTransport, n(256, 108), "profit", 3],
  ["Fashionable Heat Pumps", renewableEnergy, n(512, 108), "profit", 3],
  ["Shoulder Strap Magnets", cern, n(1, 111), "profit", 3],
  ["Elevator Music", "all", n(100, 111), "profit", 9],
  ["Spring-Loaded Trays", ikeaMeatball, n(125, 111), "profit", 2],
  ["Effective Custodians", gdprCompliance, n(150, 111), "profit", 2],
  ["Goatee Allowance", parentalLeave, n(175, 111), "profit", 2],
  ["Crash Insurance", lovableCredits, n(200, 111), "profit", 2],
  ["Ultimate Pinball Cabinet", berghainClub, n(225, 111), "profit", 2],
  ["Rustic Voice Lessons", elevenLabsDj, n(250, 111), "profit", 2],
  ["Salt-Free Caps", tetheredBottleCap, n(275, 111), "profit", 2],
  ["Bus Lane Expansion", publicTransport, n(300, 111), "profit", 2],
  ["District Heating", renewableEnergy, n(350, 111), "profit", 2],
  ["The On-Off Switch", cern, n(400, 111), "profit", 2],
  ["Free Crepe Thursdays", "all", n(500, 111), "profit", 9],
  ["Rocket Meatballs", ikeaMeatball, n(1, 114), "profit", 11],
  ["Causality Disruptors", gdprCompliance, n(10, 114), "profit", 11],
  ["Rapid Evolution", parentalLeave, n(100, 114), "profit", 11],
  ["Teeny Tiny Tokens", lovableCredits, n(1, 117), "profit", 11],
  ["Velvet Napkins", berghainClub, n(10, 117), "profit", 11],
  ["Beard Microphones", elevenLabsDj, n(100, 117), "profit", 11],
  ["Nose-Friendly Caps", tetheredBottleCap, n(1, 120), "profit", 11],
  ["Transit Protocols", publicTransport, n(10, 120), "profit", 11],
  ["Bacon-Carbon Capture", renewableEnergy, n(100, 120), "profit", 11],
  ["Out-Of-Place Particles", cern, n(1, 123), "profit", 11],
  ["Flat-Pack Robotic Cafeteria", ikeaMeatball, n(1, 123), "profit", 3],
  ["Continental Data Treaty", gdprCompliance, n(7, 123), "profit", 3],
  ["Mandatory 4-Week Holiday", parentalLeave, n(29, 123), "profit", 3],
  ["Self-Healing Codebase", lovableCredits, n(66, 123), "profit", 3],
  ["Eternal Door Queue", berghainClub, n(129, 123), "profit", 3],
  ["Telepathic Voice Sync", elevenLabsDj, n(233, 123), "profit", 3],
  ["Single-Cap Eternity", tetheredBottleCap, n(555, 123), "profit", 3],
  ["Continental Conductor Pool", publicTransport, n(900, 123), "profit", 3],
  ["Antimatter-Wind Hybrid", renewableEnergy, n(3, 126), "profit", 3],
  ["Multiverse Particle Tap", cern, n(20, 126), "profit", 3],
  ["The Mega Upgrade", "all", n(10, 123), "profit", 15],
  ["Giant Domes", "all", n(111, 129), "profit", 9],
  ["Digieurope", "all", n(1, 135), "profit", 9],
  ["Eternal Lingonberry Loop", ikeaMeatball, n(1, 138), "profit", 3],
  ["Continental Compliance Oath", gdprCompliance, n(2, 138), "profit", 3],
  ["Centennial Sabbatical", parentalLeave, n(3, 138), "profit", 3],
  ["Centennial Prompt Library", lovableCredits, n(4, 138), "profit", 3],
  ["Eternal Underground Beat", berghainClub, n(5, 138), "profit", 3],
  ["Hundred-Voice Choir", elevenLabsDj, n(6, 138), "profit", 3],
  ["Eternal Recyclable Polymer", tetheredBottleCap, n(7, 138), "profit", 3],
  ["Eternal Tram Pass", publicTransport, n(8, 138), "profit", 3],
  ["Eternal Wind Harvest", renewableEnergy, n(9, 138), "profit", 3],
  ["Beam-Powered Eternity", cern, n(10, 138), "profit", 3],
  ["Thneed Sales", "all", n(100, 138), "profit", 9],
  ["Continent-Wide Cafeteria Chain", ikeaMeatball, n(1, 141), "profit", 3],
  ["Pan-European Audit Council", gdprCompliance, n(3, 141), "profit", 3],
  ["Year-Long Paternity Tier", parentalLeave, n(7, 141), "profit", 3],
  ["Lifetime Prompt Token Bank", lovableCredits, n(25, 141), "profit", 3],
  ["Marathon Set Times", berghainClub, n(75, 141), "profit", 3],
  ["Living Voice Archive", elevenLabsDj, n(151, 141), "profit", 3],
  ["Hyper-Tethered Cap Saver", tetheredBottleCap, n(300, 141), "profit", 3],
  ["Capital-To-Capital Express", publicTransport, n(600, 141), "profit", 3],
  ["Subterranean Geothermal Loop", renewableEnergy, n(900, 141), "profit", 3],
  ["Beyond-Standard-Model Detector", cern, n(1200, 141), "profit", 3],
  ["Euroagement", "all", n(1, 153), "profit", 9],
  ["Continent-Spanning Cafeteria", ikeaMeatball, n(23, 159), "profit", 5],
  ["Sovereign-Grade Encryption", gdprCompliance, n(47, 159), "profit", 5],
  ["Multi-Generational Leave", parentalLeave, n(11, 159), "profit", 5],
  ["Self-Authoring Codebase", lovableCredits, n(24, 159), "profit", 5],
  ["Mythic Door Discretion", berghainClub, n(48, 159), "profit", 5],
  ["Pan-Linguistic Voice Stack", elevenLabsDj, n(95, 159), "profit", 5],
  ["Indestructible Cap-Bond", tetheredBottleCap, n(191, 159), "profit", 5],
  ["Continental Tram Mesh", publicTransport, n(383, 159), "profit", 5],
  ["Solar Megaproject", renewableEnergy, n(767, 159), "profit", 5],
  ["Particle Collider Encore", cern, n(5000, 159), "profit", 5],
  ["Lunatics Anonymous", "all", n(125, 162), "profit", 9],
  ["Harvest Season", "all", n(1, 165), "profit", 9],
  ["Self-Stacking Furniture", ikeaMeatball, n(1, 168), "profit", 3],
  ["Hyper-Granular Consent UI", gdprCompliance, n(14, 168), "profit", 3],
  ["Sabbatical Acceleration", parentalLeave, n(114, 168), "profit", 3],
  ["One-Click Production Deploy", lovableCredits, n(234, 168), "profit", 3],
  ["Encrypted VIP Lists", berghainClub, n(444, 168), "profit", 3],
  ["Continental Voice Festival", elevenLabsDj, n(888, 168), "profit", 3],
  ["Tether-Audit Inspection Bots", tetheredBottleCap, n(23000, 168), "profit", 3],
  ["Hyperloop Cooperation Pact", publicTransport, n(99000, 168), "profit", 3],
  ["Solar Storm Battery Storage", renewableEnergy, n(423000, 168), "profit", 3],
  ["Particle Audit Pipeline", cern, n(567000, 168), "profit", 3],
  ["Celestial Body", "all", n(899, 171), "profit", 9],
  ["Meatball Singularity", ikeaMeatball, n(1, 177), "profit", 3],
  ["Privacy Singularity", gdprCompliance, n(3, 177), "profit", 3],
  ["Endless Paternity", parentalLeave, n(9, 177), "profit", 3],
  ["Codeless Universe", lovableCredits, n(27, 177), "profit", 3],
  ["Infinite Door Curation", berghainClub, n(81, 177), "profit", 3],
  ["All-Voice Universal Choir", elevenLabsDj, n(234, 177), "profit", 3],
  ["All-Cap Tether Network", tetheredBottleCap, n(356, 177), "profit", 3],
  ["Universal Transit Mesh", publicTransport, n(432, 177), "profit", 3],
  ["Solar System Power Grid", renewableEnergy, n(567, 177), "profit", 3],
  ["Cosmic Beam Loop", cern, n(836, 177), "profit", 3],
  ["Cookies", "all", n(1, 180), "profit", 9],
  ["Lifetime Lingonberry Pass", ikeaMeatball, n(10, 183), "profit", 15],
  ["Dental Records Anonymizer", gdprCompliance, n(100, 183), "profit", 15],
  ["Annual Tax Holiday", parentalLeave, n(1, 186), "profit", 15],
  ["Overpowered Prompt Compiler", lovableCredits, n(10, 186), "profit", 15],
  ["Self-Cooling Dance Floor", berghainClub, n(100, 186), "profit", 15],
  ["Ambitious Voice Cloning", elevenLabsDj, n(1, 189), "profit", 15],
  ["The Cap Stands Tethered", tetheredBottleCap, n(10, 189), "profit", 15],
  ["Cryo-Conducted Trains", publicTransport, n(100, 189), "profit", 15],
  ["Romantic Solar Sunsets", renewableEnergy, n(1, 192), "profit", 15],
  ["The Big Red LHC Button", cern, n(10, 192), "profit", 15],
  ["The Very Large EU Upgrade", "all", n(100, 192), "profit", 999],
];

export const europeAngelUpgradeRows: UpgradeRow[] = [
  ["It Begins Again", "all", n(11, 3), "profit", 3],
  ["Sacred Lingonberry Steps", ikeaMeatball, n(222, 3), "profit", 3],
  ["Unseen GDPR Force", gdprCompliance, n(3, 6), "profit", 3],
  ["Soulful Sabbaticals", parentalLeave, n(4, 6), "profit", 3],
  ["Heavenly Prompt Wings", lovableCredits, n(55, 6), "profit", 3],
  ["Underground Spirits", berghainClub, n(666, 6), "profit", 3],
  ["Sacred Audio Ground", elevenLabsDj, n(7, 9), "profit", 3],
  ["Cap Tether Connoisseurs", tetheredBottleCap, n(88, 9), "profit", 3],
  ["Group Pass Discounts", publicTransport, n(999, 9), "profit", 3],
  ["Wind-Powered BBQs", renewableEnergy, n(1, 12), "profit", 3],
  ["Beam Target Practice", cern, n(11, 12), "profit", 3],
  ["Continental Lunatics", "all", n(123, 12), "profit", 3],
  ["GDPR Booth Swap", gdprCompliance, n(50, 18), "owned", 10],
  ["Lovable Swap", lovableCredits, n(50, 18), "owned", 10],
  ["Voice Farm Swap", elevenLabsDj, n(50, 18), "owned", 10],
  ["Tram Swap", publicTransport, n(50, 18), "owned", 10],
  ["Beam Swap", cern, n(50, 18), "owned", 10],
  ["IKEA Sandal Line", ikeaMeatball, n(1, 21), "profit", 3],
  ["Featherlight Consent", gdprCompliance, n(9, 21), "profit", 3],
  ["Holy Job-Share", parentalLeave, n(27, 21), "profit", 3],
  ["Miraculous Pricing Tier", lovableCredits, n(99, 21), "profit", 3],
  ["Lifetime Club Memberships", berghainClub, n(180, 21), "profit", 3],
  ["Extra Voice Tracks", elevenLabsDj, n(222, 21), "profit", 3],
  ["Cheap Cap Engineering", tetheredBottleCap, n(343, 21), "profit", 3],
  ["Express Pass-age", publicTransport, n(477, 21), "profit", 3],
  ["Continental Devotion", "all", n(2, 33), "profit", 3],
  ["Cookie Booth Boost", gdprCompliance, n(100, 33), "owned", 10],
  ["Prompt Boost", lovableCredits, n(100, 33), "owned", 10],
  ["Voice Farm Boost", elevenLabsDj, n(100, 33), "owned", 10],
  ["Tram Park Boost", publicTransport, n(100, 33), "owned", 10],
  ["Beam Boost", cern, n(100, 33), "owned", 10],
  ["Seraphic Meatball Trays", ikeaMeatball, n(5, 36), "profit", 3],
  ["Angel-Sized Consent Forms", gdprCompliance, n(19, 36), "profit", 3],
  ["Guardian Caregivers", parentalLeave, n(88, 36), "profit", 3],
  ["Celestial Code Couriers", lovableCredits, n(144, 36), "profit", 3],
  ["Angel Door Curator", berghainClub, n(201, 36), "profit", 3],
  ["Faithful Voice Servant", elevenLabsDj, n(333, 36), "profit", 3],
  ["Cherubic Cap Carriers", tetheredBottleCap, n(400, 36), "profit", 3],
  ["Righteous Fares", publicTransport, n(588, 36), "profit", 3],
  ["Wind Farm Tours", renewableEnergy, n(701, 36), "profit", 3],
  ["Hallowed Vacuum Chamber", cern, n(911, 36), "profit", 3],
  ["Devoted Continental Descent", "all", n(50, 39), "profit", 9],
  ["Consent Trade", gdprCompliance, n(5, 42), "owned", 10],
  ["Prompt Trade", lovableCredits, n(5, 42), "owned", 10],
  ["Voice Trade", elevenLabsDj, n(5, 42), "owned", 10],
  ["Tram Trade", publicTransport, n(5, 42), "owned", 10],
  ["Beam Trade", cern, n(5, 42), "owned", 10],
  ["Holy Meatball Steam Vents", ikeaMeatball, n(3, 45), "profit", 5],
  ["Gilded Compliance Frames", gdprCompliance, n(6, 45), "profit", 5],
  ["Copy-Paste Vacations", parentalLeave, n(12, 45), "profit", 5],
  ["Heavenly Dev Crew", lovableCredits, n(24, 45), "profit", 5],
  ["Designated Door Picks", berghainClub, n(48, 45), "profit", 5],
  ["Angelic Voice Crops", elevenLabsDj, n(96, 45), "profit", 5],
  ["Holy Cap Polymer", tetheredBottleCap, n(192, 45), "profit", 5],
  ["Blessed Tram Tickets", publicTransport, n(384, 45), "profit", 5],
  ["Winged Wind Spirits", renewableEnergy, n(768, 45), "profit", 5],
  ["Beams From Above", cern, n(14, 48), "profit", 5],
  ["Continental Salvation", "all", n(500, 48), "profit", 9],
  ["Continental Sonata", "all", n(100, 51), "profit", 9],
  ["Meatball Heck-Of-A-Deal", ikeaMeatball, n(5, 54), "owned", 50],
  ["GDPR Heck-Of-A-Deal", gdprCompliance, n(5, 54), "owned", 50],
  ["Leave Heck-Of-A-Deal", parentalLeave, n(5, 54), "owned", 50],
  ["Lovable Heck-Of-A-Deal", lovableCredits, n(5, 54), "owned", 50],
  ["Berghain Heck-Of-A-Deal", berghainClub, n(5, 54), "owned", 50],
  ["ElevenLabs Heck-Of-A-Deal", elevenLabsDj, n(5, 54), "owned", 50],
  ["Cap Heck-Of-A-Deal", tetheredBottleCap, n(5, 54), "owned", 50],
  ["Transit Heck-Of-A-Deal", publicTransport, n(5, 54), "owned", 50],
  ["Renewable Heck-Of-A-Deal", renewableEnergy, n(5, 54), "owned", 50],
  ["CERN Heck-Of-A-Deal", cern, n(5, 54), "owned", 50],
  ["Blessed Meatball Soles", ikeaMeatball, n(100, 54), "profit", 3],
  ["Holy Privacy Infusion", gdprCompliance, n(200, 54), "profit", 3],
  ["Blessed Caregivers", parentalLeave, n(300, 54), "profit", 3],
  ["Holy Prompt Ship", lovableCredits, n(400, 54), "profit", 3],
  ["Blessed Bartop", berghainClub, n(500, 54), "profit", 3],
  ["Holy Vocal Handprint", elevenLabsDj, n(600, 54), "profit", 3],
  ["Blessed Recyclable Polymer", tetheredBottleCap, n(700, 54), "profit", 3],
  ["Holy Tram Network", publicTransport, n(800, 54), "profit", 3],
  ["Holy Solar Pelts", renewableEnergy, n(900, 54), "profit", 3],
  ["Blessed Spectrometer", cern, n(1, 57), "profit", 3],
  ["Ceremonial European Rites", "all", n(316, 57), "profit", 3],
  ["Divine Inspiration", "all", n(1, 60), "profit", 9],
  ["Meatball ZIPPITY", ikeaMeatball, n(100, 63), "owned", 75],
  ["GDPR ZIPPITY", gdprCompliance, n(100, 63), "owned", 75],
  ["Leave ZIPPITY", parentalLeave, n(100, 63), "owned", 75],
  ["Lovable ZIPPITY", lovableCredits, n(100, 63), "owned", 75],
  ["Berghain ZIPPITY", berghainClub, n(100, 63), "owned", 75],
  ["ElevenLabs ZIPPITY", elevenLabsDj, n(100, 63), "owned", 75],
  ["Cap ZIPPITY", tetheredBottleCap, n(100, 63), "owned", 75],
  ["Transit ZIPPITY", publicTransport, n(100, 63), "owned", 75],
  ["Renewable ZIPPITY", renewableEnergy, n(100, 63), "owned", 75],
  ["CERN ZIPPITY", cern, n(100, 63), "owned", 75],
  ["Retroactive Continental Sacrifice", "all", n(1, 66), "profit", 3],
  ["Sacred Allen Keys", ikeaMeatball, n(1, 69), "profit", 3],
  ["Hallowed Privacy Filters", gdprCompliance, n(2, 69), "profit", 3],
  ["Sacred Genetics Bank", parentalLeave, n(4, 69), "profit", 3],
  ["Hallowed Captain's Prompt", lovableCredits, n(8, 69), "profit", 3],
  ["Sacred VIP Thrones", berghainClub, n(16, 69), "profit", 3],
  ["Hallowed Audio Shelter", elevenLabsDj, n(32, 69), "profit", 3],
  ["Sacred Cap Resin", tetheredBottleCap, n(64, 69), "profit", 3],
  ["Hallowed Tram Castle", publicTransport, n(128, 69), "profit", 3],
  ["Sacred Wind Scarves", renewableEnergy, n(256, 69), "profit", 3],
  ["Hollower Beam Pipe", cern, n(512, 69), "profit", 3],
  ["Continental Financial Advice", "all", n(1, 72), "profit", 9],
  ["GDPR Bargain", gdprCompliance, n(5, 75), "owned", 50],
  ["Prompt Bargain", lovableCredits, n(5, 75), "owned", 50],
  ["Berghain Super Bargain", berghainClub, n(5, 75), "owned", 100],
  ["Cap Super Bargain", tetheredBottleCap, n(5, 75), "owned", 100],
  ["Beam Bargain", cern, n(5, 75), "owned", 25],
  ["On The Lingonberry Floor", ikeaMeatball, n(100, 75), "profit", 7],
  ["The Over-Consent", gdprCompliance, n(200, 75), "profit", 7],
  ["Angelic Parental Leaves", parentalLeave, n(400, 75), "profit", 7],
  ["Express Prompt Pipeline", lovableCredits, n(800, 75), "profit", 7],
  ["Sparkling Spirits", berghainClub, n(16, 78), "profit", 7],
  ["Holy Voice Choristers", elevenLabsDj, n(32, 78), "profit", 7],
  ["Light-Up Tether Caps", tetheredBottleCap, n(64, 78), "profit", 7],
  ["Spreading Continental Joy", publicTransport, n(128, 78), "profit", 7],
  ["Angel Wind Wolves", renewableEnergy, n(256, 78), "profit", 7],
  ["Heavenly Beam Glow", cern, n(512, 78), "profit", 7],
  ["A Beautiful Continental Boost", "all", n(1, 81), "profit", 7],
  ["Lovable Hostile Takeover", lovableCredits, n(100, 84), "owned", 100],
  ["Berghain Hostile Takeover", berghainClub, n(200, 84), "owned", 200],
  ["Cap Industry Hostile Takeover", tetheredBottleCap, n(300, 84), "owned", 300],
  ["Meatball Holiday Sale", ikeaMeatball, n(1, 87), "profit", 2],
  ["GDPR Holiday Sale", gdprCompliance, n(9, 87), "profit", 2],
  ["Caregiver Holiday Sale", parentalLeave, n(18, 87), "profit", 2],
  ["Prompt Holiday Sale", lovableCredits, n(27, 87), "profit", 2],
  ["Club Holiday Sale", berghainClub, n(36, 87), "profit", 2],
  ["Voice Farm Holiday Sale", elevenLabsDj, n(45, 87), "profit", 2],
  ["Cap Holiday Sale", tetheredBottleCap, n(54, 87), "profit", 2],
  ["Tram Holiday Discount", publicTransport, n(63, 87), "profit", 2],
  ["Wind Holiday Bonus", renewableEnergy, n(72, 87), "profit", 2],
  ["Beams Don't Take Holidays", cern, n(81, 87), "profit", 2],
  ["Godspeed You Continental Emperor", "all", n(1, 90), "profit", 5],
];
